window.EXAMPLE_BANK = Object.assign(window.EXAMPLE_BANK || {}, {
  "believe": ["I believe his story.", "私は彼の話を信じている。"],
  "consider": ["We consider her a good leader.", "私たちは彼女をよいリーダーだと考えている。"],
  "expect": ["I expect rain this afternoon.", "今日の午後は雨になると思う。"],
  "decide": ["They decided to stay home.", "彼らは家にいることに決めた。"],
  "allow": ["My parents allow me to travel alone.", "私の親は私が一人で旅行することを許している。"],
  "remember": ["I remember her name clearly.", "私は彼女の名前をはっきり覚えている。"],
  "worry": ["Don’t worry about the test.", "そのテストのことを心配しないで。"],
  "concern": ["This problem concerns all students.", "この問題はすべての生徒に関係している。"],
  "suggest": ["She suggested a different plan.", "彼女は別の案を提案した。"],
  "explain": ["Can you explain this rule?", "このルールを説明してくれますか。"],
  "describe": ["Please describe your hometown.", "あなたの故郷について説明してください。"],
  "improve": ["Reading daily improves your English.", "毎日読むことは英語力を高める。"],
  "produce": ["This farm produces fresh vegetables.", "この農場は新鮮な野菜を生産している。"],
  "create": ["The artist created a beautiful painting.", "その芸術家は美しい絵を創作した。"],
  "provide": ["The hotel provides free breakfast.", "そのホテルは無料の朝食を提供している。"],
  "increase": ["Prices increased last month.", "先月、物価が上がった。"],
  "grow": ["Children grow quickly.", "子どもはすぐ成長する。"],
  "develop": ["They developed a new app.", "彼らは新しいアプリを開発した。"],
  "rise": ["The sun rises early in summer.", "夏は太陽が早く昇る。"],
  "raise": ["They raised three children.", "彼らは3人の子どもを育てた。"],
  "follow": ["Please follow these instructions.", "これらの指示に従ってください。"],
  "require": ["This job requires computer skills.", "この仕事にはコンピューター技能が必要だ。"],
  "fill": ["She filled the bottle with water.", "彼女はそのびんを水でいっぱいにした。"],
  "support": ["I support your decision.", "私はあなたの決定を支持する。"],
  "share": ["We shared a large pizza.", "私たちは大きなピザを分け合った。"],
  "face": ["We faced many problems.", "私たちは多くの問題に直面した。"],
  "touch": ["Her speech touched my heart.", "彼女のスピーチは私の心を打った。"],
  "store": ["We store rice in this box.", "私たちはこの箱に米を保存している。"],
  "pay": ["I paid for lunch.", "私は昼食代を払った。"],
  "deal": ["She deals with customer complaints.", "彼女は顧客からの苦情に対応している。"],
  "save": ["Walking saves money.", "歩くことはお金の節約になる。"],
  "happen": ["Accidents happen sometimes.", "事故はときどき起こる。"],
  "occur": ["The mistake occurred yesterday.", "そのミスは昨日起こった。"],
  "work": ["My phone doesn’t work.", "私のスマホは動かない。"],
  "change": ["Time changes people.", "時は人を変える。"],
  "run": ["She runs a small café.", "彼女は小さなカフェを経営している。"],
  "turn": ["Turn the handle slowly.", "取っ手をゆっくり回してください。"],
  "return": ["He returned home late.", "彼は遅く帰宅した。"],
  "stand": ["I can’t stand loud music.", "私は大きな音の音楽に耐えられない。"],
  "lie": ["He lay on the sofa.", "彼はソファに横たわった。"],
  "brain": ["The brain controls the body.", "脳は体をコントロールしている。"],
  "mind": ["I changed my mind.", "私は考えを変えた。"],
  "language": ["English is a global language.", "英語は世界的な言語だ。"],
  "thought": ["That thought made me smile.", "その考えが私を笑顔にした。"],
  "knowledge": ["Knowledge grows through study.", "知識は学習によって増える。"],
  "skill": ["Cooking is a useful skill.", "料理は役に立つ技能だ。"],
  "technology": ["Technology changes our lives.", "科学技術は私たちの生活を変える。"],
  "culture": ["I enjoy learning about Japanese culture.", "私は日本文化について学ぶことを楽しんでいる。"],
  "experience": ["Teaching gave me valuable experience.", "教えることは私に貴重な経験を与えてくれた。"],
  "result": ["Hard work brings good results.", "努力はよい結果をもたらす。"],
  "reason": ["What is the reason?", "理由は何ですか。"],
  "cause": ["Stress can cause headaches.", "ストレスは頭痛を引き起こすことがある。"],
  "effect": ["The medicine had a quick effect.", "その薬はすぐに効果があった。"],
  "matter": ["Health matters most.", "健康が何より大切だ。"],
  "sense": ["Dogs have a strong sense of smell.", "犬は強い嗅覚を持っている。"],
  "way": ["This is the best way.", "これが最善の方法だ。"],
  "term": ["We learned a new scientific term.", "私たちは新しい科学用語を学んだ。"],
  "situation": ["The situation is getting worse.", "状況は悪化している。"],
  "condition": ["His condition is improving.", "彼の容体はよくなっている。"],
  "position": ["She is in a difficult position.", "彼女は難しい立場にいる。"],
  "environment": ["We must protect the environment.", "私たちは環境を守らなければならない。"],
  "nature": ["She loves nature.", "彼女は自然が大好きだ。"],
  "research": ["He is doing cancer research.", "彼はがん研究をしている。"],
  "rule": ["School rules are strict.", "学校の規則は厳しい。"],
  "interest": ["She has an interest in art.", "彼女は芸術に興味がある。"],
  "value": ["Time has great value.", "時間には大きな価値がある。"],
  "view": ["I agree with your view.", "私はあなたの意見に賛成だ。"],
  "sound": ["I heard a strange sound.", "私は変な音を聞いた。"],
  "form": ["Please fill out this form.", "この用紙に記入してください。"],
  "case": ["In this case, we should wait.", "この場合、私たちは待つべきだ。"],
  "role": ["Parents play an important role.", "親は重要な役割を果たす。"],
  "age": ["Children start school at age six.", "子どもは6歳で学校に通い始める。"],
  "care": ["Babies need constant care.", "赤ちゃんには絶え間ない世話が必要だ。"],
  "risk": ["Smoking increases the risk of disease.", "喫煙は病気の危険性を高める。"],
  "human": ["Humans need sleep.", "人間には睡眠が必要だ。"],
  "free": ["Admission is free today.", "今日は入場無料だ。"],
  "sure": ["I’m sure about that.", "私はそれを確信している。"],
  "certain": ["I’m certain he called.", "彼が電話したのは確かだ。"],
  "main": ["The main reason is simple.", "主な理由は単純だ。"],
  "major": ["This is a major problem.", "これは大きな問題だ。"],
  "minor": ["He had a minor injury.", "彼は軽いけがをした。"],
  "clear": ["Her explanation was clear.", "彼女の説明は明確だった。"],
  "likely": ["Rain is likely tomorrow.", "明日は雨が降りそうだ。"],
  "possible": ["Is it possible to change seats?", "席を変えることは可能ですか。"],
  "similar": ["Our ideas are similar.", "私たちの考えは似ている。"],
  "close": ["My school is close to the station.", "私の学校は駅に近い。"],
  "common": ["Colds are common in winter.", "風邪は冬によくある。"],
  "general": ["This is a general rule.", "これは一般的な規則だ。"],
  "ordinary": ["It was an ordinary day.", "それは普通の日だった。"],
  "specific": ["Please give a specific example.", "具体的な例を挙げてください。"],
  "particular": ["She showed particular interest in music.", "彼女は音楽に特に興味を示した。"],
  "individual": ["Each student has individual needs.", "それぞれの生徒に個別の必要がある。"],
  "unique": ["Every child is unique.", "すべての子どもは唯一無二だ。"],
  "rare": ["Snow is rare here.", "ここでは雪は珍しい。"],
  "therefore": ["He was ill; therefore, he stayed home.", "彼は病気だった。したがって、家にいた。"],
  "thus": ["She studied hard and thus passed.", "彼女は一生懸命勉強し、その結果合格した。"],
  "moreover": ["The room is cheap; moreover, it is clean.", "その部屋は安い。さらに、清潔だ。"],
  "furthermore": ["He is kind; furthermore, he is honest.", "彼は親切だ。そのうえ正直でもある。"],
  "besides": ["I’m busy; besides, I’m tired.", "私は忙しい。しかも疲れている。"],
  "nonetheless": ["It was raining; nonetheless, we went out.", "雨が降っていた。それでも私たちは出かけた。"],

  "notice": ["I noticed a small mistake.", "私は小さな間違いに気づいた。"],
  "note": ["Please note the deadline.", "締め切りに注意してください。"],
  "discover": ["They discovered a hidden cave.", "彼らは隠れた洞くつを発見した。"],
  "realize": ["I realized my mistake.", "私は自分の間違いに気づいた。"],
  "recognize": ["I recognized her voice immediately.", "私はすぐに彼女の声だとわかった。"],
  "encourage": ["Teachers should encourage students.", "教師は生徒を励ますべきだ。"],
  "force": ["The rain forced us inside.", "雨のせいで私たちは中に入らざるを得なかった。"],
  "order": ["We ordered two pizzas.", "私たちはピザを2枚注文した。"],
  "affect": ["Lack of sleep affects health.", "睡眠不足は健康に影響する。"],
  "offer": ["He offered me some help.", "彼は私に手助けを申し出てくれた。"],
  "demand": ["Customers demand better service.", "顧客はよりよいサービスを求める。"],
  "argue": ["They argued about money.", "彼らはお金について口論した。"],
  "claim": ["She claimed the bag was hers.", "彼女はそのかばんは自分のものだと主張した。"],
  "object": ["I object to that idea.", "私はその考えに反対する。"],
  "challenge": ["She challenged his opinion.", "彼女は彼の意見に異議を唱えた。"],
  "involve": ["The job involves long hours.", "その仕事には長時間労働が伴う。"],
  "include": ["The price includes breakfast.", "その料金には朝食が含まれている。"],
  "contain": ["This box contains old photos.", "この箱には古い写真が入っている。"],
  "relate": ["I can relate to his feelings.", "私は彼の気持ちに共感できる。"],
  "connect": ["This road connects two towns.", "この道路は2つの町をつないでいる。"],
  "refer": ["He referred to that article.", "彼はその記事に言及した。"],
  "contact": ["Please contact me tomorrow.", "明日私に連絡してください。"],
  "compare": ["Compare these two pictures.", "この2枚の写真を比べなさい。"],
  "measure": ["We measured the room.", "私たちはその部屋の大きさを測った。"],
  "mark": ["Please mark the correct answer.", "正しい答えに印をつけてください。"],
  "approach": ["A car approached slowly.", "1台の車がゆっくり近づいてきた。"],
  "reach": ["We reached the station at noon.", "私たちは正午に駅に着いた。"],
  "achieve": ["She achieved her goal.", "彼女は目標を達成した。"],
  "receive": ["I received your email.", "あなたのメールを受け取りました。"],
  "complete": ["He completed the report.", "彼は報告書を完成させた。"],
  "lead": ["Good teachers lead by example.", "よい教師は手本を示して導く。"],
  "win": ["Our team won the game.", "私たちのチームは試合に勝った。"],
  "lose": ["Be careful not to lose your key.", "鍵をなくさないように気をつけて。"],
  "fail": ["He failed to keep his promise.", "彼は約束を守れなかった。"],
  "miss": ["I missed the last bus.", "私は終バスに乗り遅れた。"],
  "lack": ["The team lacks experience.", "そのチームは経験に欠けている。"],
  "reduce": ["We need to reduce waste.", "私たちは無駄を減らす必要がある。"],
  "avoid": ["Avoid drinking too much coffee.", "コーヒーを飲みすぎるのは避けなさい。"],
  "limit": ["The rule limits screen time.", "そのルールは画面を見る時間を制限する。"],
  "prevent": ["Warm clothes prevent illness.", "暖かい服は病気の予防になる。"],
  "wear": ["She wore a red coat.", "彼女は赤いコートを着ていた。"],
  "bear": ["I can’t bear the pain.", "私はその痛みに耐えられない。"],
  "focus": ["Please focus on your work.", "自分の作業に集中してください。"],
  "author": ["The author wrote five novels.", "その作家は5冊の小説を書いた。"],
  "professor": ["The professor gave a clear lecture.", "その教授はわかりやすい講義をした。"],
  "sentence": ["This sentence is too long.", "この文は長すぎる。"],
  "passage": ["Read the passage carefully.", "その一節を注意深く読みなさい。"],
  "message": ["I got your message.", "あなたのメッセージを受け取った。"],
  "statement": ["His statement surprised everyone.", "彼の発言はみんなを驚かせた。"],
  "topic": ["Today’s topic is climate change.", "今日の話題は気候変動だ。"],
  "article": ["I read an interesting article.", "私は面白い記事を読んだ。"],
  "issue": ["This is a serious issue.", "これは深刻な問題だ。"],
  "theory": ["His theory sounds reasonable.", "彼の理論はもっともらしく聞こえる。"],
  "evidence": ["There is no clear evidence.", "明確な証拠はない。"],
  "experiment": ["The students did a simple experiment.", "生徒たちは簡単な実験をした。"],
  "subject": ["Math is my favorite subject.", "数学は私の好きな科目だ。"],
  "government": ["The government announced a new plan.", "政府は新しい計画を発表した。"],
  "policy": ["The school changed its policy.", "その学校は方針を変えた。"],
  "education": ["Education shapes the future.", "教育は未来を形作る。"],
  "company": ["She works for a food company.", "彼女は食品会社で働いている。"],
  "colleague": ["My colleague helped me today.", "今日、同僚が私を助けてくれた。"],
  "industry": ["The tourism industry grew quickly.", "観光産業は急速に成長した。"],
  "trade": ["International trade supports many jobs.", "国際貿易は多くの仕事を支えている。"],
  "economy": ["The economy is improving slowly.", "経済はゆっくり改善している。"],
  "customer": ["The customer asked for help.", "その客は助けを求めた。"],
  "benefit": ["Exercise has many benefits.", "運動には多くの利点がある。"],
  "figure": ["Look at figure two.", "図2を見なさい。"],
  "rate": ["The birth rate is falling.", "出生率は下がっている。"],
  "chance": ["I had a chance to speak.", "私は話す機会があった。"],
  "opportunity": ["This job offers a great opportunity.", "この仕事はすばらしい機会を与えてくれる。"],
  "project": ["Our class started a new project.", "私たちのクラスは新しい企画を始めた。"],
  "practice": ["Daily practice improves speaking skills.", "毎日の練習は話す力を高める。"],
  "effort": ["Success requires effort.", "成功には努力が必要だ。"],
  "quality": ["This shop sells high-quality bread.", "この店は質の高いパンを売っている。"],
  "quantity": ["We need a large quantity of water.", "私たちには大量の水が必要だ。"],
  "amount": ["He spent a small amount.", "彼は少額を使った。"],
  "scientific": ["They need scientific evidence.", "彼らには科学的な証拠が必要だ。"],
  "political": ["They discussed political issues.", "彼らは政治的な問題について話し合った。"],
  "social": ["Social media spreads news fast.", "SNSはニュースを素早く広める。"],
  "official": ["This is the official answer.", "これが公式の答えだ。"],
  "financial": ["They face financial problems.", "彼らは経済的な問題に直面している。"],
  "expensive": ["This watch is too expensive.", "この時計は高すぎる。"],
  "various": ["The store sells various snacks.", "その店はいろいろなお菓子を売っている。"],
  "normal": ["It’s normal to feel nervous.", "緊張するのは普通のことだ。"],
  "familiar": ["Her face looks familiar.", "彼女の顔には見覚えがある。"],
  "appropriate": ["Jeans are not appropriate here.", "ここではジーンズは適切ではない。"],
  "necessary": ["Sleep is necessary for health.", "睡眠は健康に必要だ。"],
  "correct": ["Your answer is correct.", "あなたの答えは正しい。"],
  "available": ["Tickets are still available.", "チケットはまだ手に入る。"],
  "typical": ["It was a typical summer day.", "それは典型的な夏の日だった。"],
  "positive": ["She has a positive attitude.", "彼女は前向きな態度を持っている。"],
  "negative": ["He gave a negative answer.", "彼は否定的な返事をした。"],
  "passive": ["He stayed passive during the meeting.", "彼は会議の間、受け身のままだった。"],
  "physical": ["Physical exercise reduces stress.", "身体運動はストレスを減らす。"],
  "mental": ["Reading supports mental health.", "読書は心の健康を支える。"],
  "rather": ["The test was rather difficult.", "そのテストはかなり難しかった。"],
  "instead": ["We walked instead of driving.", "私たちは車を使わず歩いた。"],
  "otherwise": ["Hurry, otherwise you’ll be late.", "急ぎなさい。さもないと遅れるよ。"],
  "somehow": ["We somehow solved the problem.", "私たちはどうにかその問題を解決した。"],
  "somewhat": ["I was somewhat surprised.", "私はいくぶん驚いた。"],

  "wonder": ["I wonder why she left early.", "彼女がなぜ早く帰ったのかと思う。"],
  "suppose": ["I suppose he is busy.", "彼は忙しいのだと思う。"],
  "imagine": ["Imagine living by the sea.", "海のそばで暮らすことを想像してみて。"],
  "regard": ["We regard him as a friend.", "私たちは彼を友人だとみなしている。"],
  "wish": ["I wish you good luck.", "あなたの幸運を祈ります。"],
  "determine": ["The test determines your level.", "そのテストはあなたのレベルを決める。"],
  "express": ["She expressed her opinion clearly.", "彼女は自分の意見をはっきり表現した。"],
  "represent": ["This flag represents peace.", "この旗は平和を表している。"],
  "identify": ["Police identified the driver.", "警察はその運転手を特定した。"],
  "mention": ["He mentioned your name.", "彼はあなたの名前に言及した。"],
  "solve": ["We solved the math problem.", "私たちはその数学の問題を解いた。"],
  "prove": ["Can you prove that claim?", "その主張を証明できますか。"],
  "communicate": ["We communicate by email.", "私たちはメールで連絡を取り合う。"],
  "respect": ["Students respect her deeply.", "生徒たちは彼女を深く尊敬している。"],
  "prefer": ["I prefer tea to coffee.", "私はコーヒーよりお茶のほうが好きだ。"],
  "design": ["She designed a new logo.", "彼女は新しいロゴを設計した。"],
  "establish": ["They established a small school.", "彼らは小さな学校を設立した。"],
  "found": ["Her grandfather founded the company.", "彼女の祖父はその会社を設立した。"],
  "publish": ["The paper published his article.", "その新聞は彼の記事を掲載した。"],
  "serve": ["This tool serves a useful purpose.", "この道具は役に立つ目的を果たす。"],
  "supply": ["They supply fresh milk daily.", "彼らは毎日新鮮な牛乳を供給している。"],
  "apply": ["I applied for the job.", "私はその仕事に応募した。"],
  "treat": ["Doctors treated the injured man.", "医師たちはそのけが人を治療した。"],
  "search": ["They searched the room carefully.", "彼らはその部屋を注意深く捜索した。"],
  "prepare": ["We prepared for the test.", "私たちはテストの準備をした。"],
  "protect": ["Trees protect the soil.", "木は土壌を守る。"],
  "pick": ["She picked some flowers.", "彼女はいくつか花を摘んだ。"],
  "fit": ["These shoes fit me well.", "この靴は私によく合う。"],
  "gain": ["He gained useful experience abroad.", "彼は海外で役立つ経験を得た。"],
  "enter": ["She entered the classroom quietly.", "彼女は静かに教室に入った。"],
  "spread": ["The news spread quickly.", "その知らせはすぐに広まった。"],
  "advance": ["Science advances every year.", "科学は毎年進歩する。"],
  "tend": ["Children tend to copy adults.", "子どもは大人をまねしがちだ。"],
  "depend": ["Success depends on effort.", "成功は努力にかかっている。"],
  "exist": ["Dinosaurs no longer exist.", "恐竜はもはや存在しない。"],
  "decline": ["Sales declined last year.", "売り上げは去年減少した。"],
  "decrease": ["The number decreased sharply.", "その数は急激に減った。"],
  "waste": ["Don’t waste your time.", "時間を無駄にしてはいけない。"],
  "damage": ["Heavy rain damaged the road.", "大雨が道路に被害を与えた。"],
  "suffer": ["Many people suffered from hunger.", "多くの人が飢えに苦しんだ。"],
  "act": ["We must act now.", "私たちは今行動しなければならない。"],
  "perform": ["The band performed well.", "そのバンドはうまく演奏した。"],
  "species": ["This bird species is rare.", "この鳥の種は珍しい。"],
  "variety": ["The market offers great variety.", "その市場には多くの種類がある。"],
  "degree": ["The water reached twenty degrees.", "水温は20度に達した。"],
  "range": ["Prices range from ten to fifty dollars.", "価格は10ドルから50ドルまでの範囲だ。"],
  "standard": ["The work meets our standards.", "その仕事は私たちの基準を満たしている。"],
  "medium": ["Television is a powerful medium.", "テレビは強力な媒体だ。"],
  "advantage": ["Experience gives you an advantage.", "経験はあなたに有利さを与える。"],
  "task": ["My first task is cleaning.", "私の最初の仕事は掃除だ。"],
  "rest": ["You need some rest.", "少し休む必要がある。"],
  "purpose": ["What is the purpose of this meeting?", "この会議の目的は何ですか。"],
  "feature": ["The phone has useful features.", "その電話には便利な機能がある。"],
  "factor": ["Cost is an important factor.", "費用は重要な要因だ。"],
  "shape": ["Exercise keeps you in shape.", "運動は体調を保つのに役立つ。"],
  "image": ["The ad improved the company’s image.", "その広告は会社のイメージをよくした。"],
  "detail": ["Tell me the details later.", "詳しいことはあとで教えて。"],
  "character": ["He has a kind character.", "彼は親切な性格をしている。"],
  "function": ["The machine has two functions.", "その機械には2つの機能がある。"],
  "structure": ["The bridge has a strong structure.", "その橋は頑丈な構造をしている。"],
  "ground": ["The ball fell to the ground.", "ボールは地面に落ちた。"],
  "influence": ["Parents influence their children strongly.", "親は子どもに強く影響を与える。"],
  "disease": ["Smoking can cause disease.", "喫煙は病気を引き起こすことがある。"],
  "pain": ["He felt sharp pain.", "彼は鋭い痛みを感じた。"],
  "medicine": ["Take this medicine after meals.", "この薬は食後に飲んでください。"],
  "death": ["The news of his death shocked us.", "彼の死の知らせは私たちを驚かせた。"],
  "fear": ["She showed no fear.", "彼女は恐れを見せなかった。"],
  "memory": ["That song brings back memories.", "その歌は思い出をよみがえらせる。"],
  "emotion": ["Music can express deep emotion.", "音楽は深い感情を表現できる。"],
  "movement": ["The movement gained support quickly.", "その運動はすぐに支持を集めた。"],
  "region": ["Rice grows well in this region.", "この地域では米がよく育つ。"],
  "climate": ["The climate here is mild.", "ここの気候はおだやかだ。"],
  "temperature": ["The temperature dropped suddenly.", "気温が急に下がった。"],
  "community": ["The community built a new park.", "地域社会は新しい公園を作った。"],
  "population": ["The city’s population is growing.", "その市の人口は増えている。"],
  "generation": ["Each generation faces new problems.", "どの世代も新しい問題に直面する。"],
  "present": ["All students were present today.", "今日はすべての生徒が出席していた。"],
  "recent": ["Recent studies show good results.", "最近の研究はよい結果を示している。"],
  "current": ["The current plan seems practical.", "現在の計画は現実的に思える。"],
  "ancient": ["They visited an ancient temple.", "彼らは古代の寺院を訪れた。"],
  "previous": ["I missed the previous class.", "私は前の授業を休んだ。"],
  "serious": ["This is a serious mistake.", "これは重大な間違いだ。"],
  "careful": ["Be careful with that knife.", "そのナイフには気をつけて。"],
  "responsible": ["She is responsible for the project.", "彼女はその企画の責任者だ。"],
  "active": ["He stays active every day.", "彼は毎日活発に過ごしている。"],
  "afraid": ["I’m afraid of dogs.", "私は犬が怖い。"],
  "aware": ["Are you aware of the risk?", "その危険に気づいていますか。"],
  "patient": ["Please be patient with him.", "彼には辛抱強く接してください。"],
  "whole": ["I spent the whole day reading.", "私は一日中読書をして過ごした。"],
  "low": ["The table is too low.", "そのテーブルは低すぎる。"],
  "huge": ["They built a huge stadium.", "彼らは巨大な競技場を建てた。"],
  "blank": ["Please leave this line blank.", "この行は空白のままにしてください。"],
  "central": ["The station is in a central area.", "その駅は中心部にある。"],
  "safe": ["The children are safe now.", "子どもたちは今安全だ。"],
  "wild": ["We saw wild deer.", "私たちは野生の鹿を見た。"],
  "eventually": ["He eventually found a job.", "彼は結局仕事を見つけた。"],
  "unfortunately": ["Unfortunately, the store was closed.", "残念ながら、その店は閉まっていた。"],
  "seemingly": ["She was seemingly calm.", "彼女は見たところ落ち着いていた。"],
  "afterward": ["We went home afterward.", "そのあと私たちは家に帰った。"],
  "altogether": ["I’m altogether against the idea.", "私はその考えに全面的に反対だ。"]
});
Object.assign(window.EXAMPLE_BANK, {
  "assume": ["Don’t assume the answer is easy.", "その答えが簡単だと思い込まないで。"],
  "guess": ["I guess he forgot.", "彼は忘れたのだと思う。"],
  "associate": ["Many people associate summer with festivals.", "多くの人は夏と祭りを結びつける。"],
  "desire": ["She desired a peaceful life.", "彼女は穏やかな生活を強く望んだ。"],
  "indicate": ["Dark clouds indicate rain.", "黒い雲は雨を示している。"],
  "respond": ["He responded politely.", "彼は丁寧に返答した。"],
  "reply": ["She replied to my email.", "彼女は私のメールに返事をした。"],
  "attempt": ["He attempted to climb the wall.", "彼はその壁を登ろうとした。"],
  "manage": ["She managed to finish on time.", "彼女は何とか時間内に終えた。"],
  "maintain": ["They maintain the park well.", "彼らはその公園をよく維持管理している。"],
  "unite": ["Sports can unite people.", "スポーツは人々を結びつけることができる。"],
  "join": ["Why don’t you join us?", "私たちに加わりませんか。"],
  "attract": ["Flowers attract bees.", "花はハチを引きつける。"],
  "match": ["This tie matches your shirt.", "このネクタイはあなたのシャツによく合う。"],
  "attack": ["A dog attacked the man.", "犬がその男性を襲った。"],
  "seek": ["Many students seek good jobs.", "多くの生徒がよい仕事を求めている。"],
  "engage": ["Students engaged in lively discussion.", "生徒たちは活発な議論に参加した。"],
  "succeed": ["She succeeded in business.", "彼女は仕事で成功した。"],
  "marry": ["She married a doctor.", "彼女は医者と結婚した。"],
  "attend": ["I attended the meeting yesterday.", "私は昨日その会議に出席した。"],
  "satisfy": ["The meal satisfied everyone.", "その食事はみんなを満足させた。"],
  "survive": ["Few plants survive there.", "そこではほとんど植物が生き残れない。"],
  "promote": ["The campaign promotes healthy eating.", "その運動は健康的な食生活を促進している。"],
  "earn": ["He earns enough money.", "彼は十分なお金を稼いでいる。"],
  "feed": ["She fed the baby.", "彼女は赤ちゃんに食べ物を与えた。"],
  "taste": ["This soup tastes great.", "このスープはとてもおいしい。"],
  "smell": ["The room smells fresh.", "その部屋はさわやかなにおいがする。"],
  "adapt": ["Children adapt to change quickly.", "子どもは変化にすぐ順応する。"],
  "adopt": ["The school adopted new rules.", "その学校は新しい規則を採用した。"],
  "adjust": ["He adjusted the mirror.", "彼は鏡の位置を調整した。"],
  "separate": ["Please separate paper from plastic.", "紙とプラスチックを分けてください。"],
  "exchange": ["We exchanged gifts.", "私たちは贈り物を交換した。"],
  "replace": ["We replaced the old chair.", "私たちは古い椅子を取り替えた。"],
  "remove": ["Please remove your shoes.", "靴を脱いでください。"],
  "release": ["The factory released harmful gas.", "その工場は有害なガスを放出した。"],
  "disappear": ["The clouds disappeared.", "雲は消えた。"],
  "observe": ["Scientists observed the stars.", "科学者たちは星を観察した。"],
  "estimate": ["Experts estimated the cost.", "専門家たちはその費用を見積もった。"],
  "reveal": ["The report revealed the truth.", "その報告書は真実を明らかにした。"],
  "emerge": ["New problems emerged.", "新たな問題が現れた。"],
  "arise": ["Questions often arise in class.", "授業ではよく質問が生じる。"],
  "citizen": ["Every citizen has rights.", "すべての市民には権利がある。"],
  "career": ["She wants a teaching career.", "彼女は教職の道に進みたいと思っている。"],
  "income": ["His income is stable.", "彼の収入は安定している。"],
  "billion": ["The company earned one billion dollars.", "その会社は10億ドルを稼いだ。"],
  "bill": ["I paid the bill.", "私は勘定を払った。"],
  "charge": ["They charge extra for delivery.", "彼らは配達に追加料金を取る。"],
  "item": ["This item is on sale.", "この品物は特売中だ。"],
  "scale": ["The problem is large in scale.", "その問題は規模が大きい。"],
  "site": ["They visited the building site.", "彼らは建設現場を訪れた。"],
  "section": ["Read section three first.", "最初に第3節を読みなさい。"],
  "crop": ["Rice is the main crop here.", "ここでは米が主要な作物だ。"],
  "diet": ["A healthy diet matters.", "健康的な食事は大切だ。"],
  "source": ["The river is our water source.", "その川は私たちの水源だ。"],
  "resource": ["Oil is a valuable resource.", "石油は貴重な資源だ。"],
  "moment": ["Wait a moment, please.", "少し待ってください。"],
  "decade": ["The town changed over the decade.", "その町はこの10年で変わった。"],
  "stage": ["He is in the final stage.", "彼は最終段階にいる。"],
  "aspect": ["We discussed every aspect.", "私たちはあらゆる側面について話し合った。"],
  "sort": ["What sort of music do you like?", "どんな種類の音楽が好きですか。"],
  "instance": ["This is one clear instance.", "これは1つの明確な例だ。"],
  "link": ["There is a link between sleep and health.", "睡眠と健康の間には関連がある。"],
  "contrast": ["The contrast was striking.", "その対照は際立っていた。"],
  "access": ["Students need internet access.", "生徒にはインターネット利用環境が必要だ。"],
  "device": ["This device saves energy.", "この装置はエネルギーを節約する。"],
  "survey": ["The survey showed high interest.", "その調査は高い関心を示した。"],
  "technique": ["He learned a new technique.", "彼は新しい技術を学んだ。"],
  "content": ["The box’s content was surprising.", "その箱の中身は驚くべきものだった。"],
  "surface": ["The table surface felt smooth.", "その机の表面はなめらかだった。"],
  "concept": ["The concept is easy to understand.", "その概念は理解しやすい。"],
  "difficulty": ["She had difficulty breathing.", "彼女は呼吸するのが苦しかった。"],
  "trouble": ["I had trouble sleeping.", "私は眠るのに苦労した。"],
  "crime": ["Crime is rising in the city.", "その市では犯罪が増えている。"],
  "attitude": ["She has a positive attitude.", "彼女は前向きな態度を持っている。"],
  "habit": ["Reading before bed is my habit.", "寝る前に読むことは私の習慣だ。"],
  "whatever": ["Whatever happens, stay calm.", "何が起きても落ち着いていなさい。"],
  "urban": ["Urban life can be stressful.", "都市生活はストレスが多いことがある。"],
  "rural": ["He grew up in a rural area.", "彼は田舎で育った。"],
  "local": ["We bought local vegetables.", "私たちは地元の野菜を買った。"],
  "native": ["She is a native speaker.", "彼女はその言語の母語話者だ。"],
  "smart": ["He is smart and kind.", "彼は頭がよくて親切だ。"],
  "intelligent": ["She is highly intelligent.", "彼女はとても聡明だ。"],
  "intellectual": ["They discussed intellectual topics.", "彼らは知的な話題について議論した。"],
  "potential": ["She has great potential.", "彼女には大きな可能性がある。"],
  "moral": ["We discussed a moral issue.", "私たちは道徳的な問題について話し合った。"],
  "private": ["This is a private matter.", "これは個人的な問題だ。"],
  "equal": ["All students deserve equal treatment.", "すべての生徒は平等に扱われるべきだ。"],
  "fair": ["The judge made a fair decision.", "その審判は公正な判断をした。"],
  "entire": ["I spent the entire evening studying.", "私は夕方ずっと勉強して過ごした。"],
  "initial": ["We faced initial problems.", "私たちは最初の問題に直面した。"],
  "essential": ["Water is essential for life.", "水は生命に不可欠だ。"],
  "significant": ["The change was significant.", "その変化は重要だった。"],
  "terrible": ["We had terrible weather.", "ひどい天気だった。"],
  "digital": ["I read a digital book.", "私は電子書籍を読んだ。"],
  "direct": ["She gave a direct answer.", "彼女は率直な答えをした。"],
  "nearly": ["I nearly missed the train.", "私は電車に乗り遅れそうになった。"],
  "merely": ["He merely smiled.", "彼はただ微笑んだだけだった。"],
  "seldom": ["We seldom eat out.", "私たちはめったに外食しない。"],
  "lately": ["I’ve been busy lately.", "私は最近ずっと忙しい。"],
  "apart": ["They live far apart.", "彼らは遠く離れて住んでいる。"],

  "trust": ["I trust her completely.", "私は彼女を完全に信頼している。"],
  "promise": ["He promised to help me.", "彼は私を助けると約束した。"],
  "predict": ["Experts predict heavy rain tomorrow.", "専門家たちは明日の大雨を予想している。"],
  "reflect": ["The water reflected the moon.", "水面に月が映っていた。"],
  "recall": ["I recall that day clearly.", "私はその日をはっきり思い出す。"],
  "rely": ["Many children rely on their parents.", "多くの子どもは親に頼っている。"],
  "commit": ["He committed a serious mistake.", "彼は重大な過ちを犯した。"],
  "appreciate": ["I appreciate your kindness.", "あなたの親切に感謝します。"],
  "praise": ["The teacher praised her effort.", "先生は彼女の努力をほめた。"],
  "doubt": ["I doubt his story.", "私は彼の話を疑っている。"],
  "complain": ["They complained about the noise.", "彼らはその騒音について不平を言った。"],
  "ignore": ["Don’t ignore warning signs.", "警告のサインを無視してはいけない。"],
  "warn": ["They warned us about the storm.", "彼らは私たちに嵐について警告した。"],
  "gather": ["We gathered around the fire.", "私たちは火の周りに集まった。"],
  "acquire": ["Children acquire language naturally.", "子どもは自然に言語を身につける。"],
  "examine": ["The doctor examined my knee.", "医者は私のひざを診察した。"],
  "score": ["She scored three goals.", "彼女は3点取った。"],
  "judge": ["Don’t judge people quickly.", "人をすぐに判断してはいけない。"],
  "select": ["Please select one answer.", "答えを1つ選んでください。"],
  "divide": ["Divide the cake into six pieces.", "そのケーキを6つに分けなさい。"],
  "distinguish": ["I can’t distinguish the twins.", "私はその双子を見分けられない。"],
  "graduate": ["She graduated from college last year.", "彼女は昨年大学を卒業した。"],
  "shift": ["Public opinion shifted quickly.", "世論はすぐに変化した。"],
  "hide": ["He hid the letter.", "彼はその手紙を隠した。"],
  "mix": ["Mix the eggs with milk.", "卵と牛乳を混ぜなさい。"],
  "fix": ["Can you fix my bike?", "私の自転車を直してくれますか。"],
  "display": ["The museum displayed ancient tools.", "その博物館は古代の道具を展示した。"],
  "define": ["Can you define this word?", "この語を定義できますか。"],
  "invent": ["He invented a useful tool.", "彼は便利な道具を発明した。"],
  "vary": ["Prices vary by season.", "価格は季節によって異なる。"],
  "expand": ["The company expanded overseas.", "その会社は海外に事業を広げた。"],
  "evolve": ["Languages evolve over time.", "言語は時とともに発達する。"],
  "confuse": ["The similar names confuse me.", "似た名前で私は混乱する。"],
  "consume": ["Cars consume a lot of fuel.", "車は多くの燃料を消費する。"],
  "compete": ["Teams compete for the title.", "チームは優勝を争う。"],
  "repeat": ["Please repeat the question.", "その質問をもう一度言ってください。"],
  "repair": ["They repaired the broken window.", "彼らは壊れた窓を修理した。"],
  "remind": ["Your smile reminds me of her.", "あなたの笑顔を見ると彼女を思い出す。"],
  "refuse": ["He refused my offer.", "彼は私の申し出を断った。"],
  "reject": ["She rejected the idea.", "彼女はその考えを拒んだ。"],
  "deny": ["He denied the rumor.", "彼はそのうわさを否定した。"],
  "destroy": ["The fire destroyed the house.", "火事がその家を破壊した。"],
  "audience": ["The audience clapped loudly.", "観客は大きな拍手を送った。"],
  "race": ["People of every race joined.", "あらゆる人種の人々が参加した。"],
  "conflict": ["The conflict lasted for years.", "その争いは何年も続いた。"],
  "debate": ["We had a debate in class.", "私たちは授業で討論をした。"],
  "struggle": ["She struggled to stay awake.", "彼女は起きていようと必死だった。"],
  "strategy": ["We need a better strategy.", "私たちにはよりよい戦略が必要だ。"],
  "progress": ["The patient is making progress.", "その患者は回復に向かっている。"],
  "principle": ["Honesty is an important principle.", "正直さは大切な原則だ。"],
  "element": ["Water contains two elements.", "水は2つの元素を含んでいる。"],
  "origin": ["No one knows the origin.", "その起源は誰にもわからない。"],
  "birth": ["The baby’s birth brought joy.", "その赤ちゃんの誕生は喜びをもたらした。"],
  "ancestor": ["My ancestors came from China.", "私の祖先は中国から来た。"],
  "cell": ["The body is made of cells.", "体は細胞でできている。"],
  "gene": ["Some diseases are linked to genes.", "いくつかの病気は遺伝子と関係している。"],
  "scene": ["The final scene was moving.", "最後の場面は感動的だった。"],
  "trend": ["Online shopping is a growing trend.", "オンラインショッピングは広がりつつある傾向だ。"],
  "traffic": ["Morning traffic was heavy.", "朝の交通量は多かった。"],
  "track": ["We found animal tracks.", "私たちは動物の足跡を見つけた。"],
  "series": ["I watched the whole series.", "私はそのシリーズを全部見た。"],
  "context": ["The word changes meaning by context.", "その語は文脈によって意味が変わる。"],
  "background": ["She has a science background.", "彼女には理系の背景がある。"],
  "basis": ["Trust is the basis of friendship.", "信頼は友情の基礎だ。"],
  "status": ["His social status changed.", "彼の社会的地位は変わった。"],
  "volunteer": ["A volunteer guided the visitors.", "ボランティアが訪問者を案内した。"],
  "staff": ["The hotel staff were helpful.", "そのホテルの職員は親切だった。"],
  "duty": ["It is our duty to help.", "助けるのは私たちの義務だ。"],
  "labor": ["Farm labor is hard work.", "農作業はきつい労働だ。"],
  "reward": ["Hard work brings reward.", "努力は報いをもたらす。"],
  "aim": ["Our aim is clear.", "私たちの目的は明確だ。"],
  "fun": ["The trip was great fun.", "その旅行はとても楽しかった。"],
  "crowd": ["A large crowd gathered outside.", "大勢の群衆が外に集まった。"],
  "revolution": ["The invention caused a revolution.", "その発明は革命を引き起こした。"],
  "poverty": ["Many children live in poverty.", "多くの子どもが貧困の中で暮らしている。"],
  "consequence": ["His actions had serious consequences.", "彼の行動は深刻な結果を招いた。"],
  "sequence": ["Put the pictures in sequence.", "その絵を順番に並べなさい。"],
  "complex": ["The system is too complex.", "その仕組みは複雑すぎる。"],
  "complicated": ["The rules seem complicated.", "その規則は複雑に思える。"],
  "false": ["That story is false.", "その話は誤りだ。"],
  "alternative": ["We need an alternative plan.", "私たちには別の案が必要だ。"],
  "extreme": ["The weather was extreme.", "天気は極端だった。"],
  "ideal": ["This room is ideal for study.", "この部屋は勉強に最適だ。"],
  "primary": ["Safety is our primary concern.", "安全が私たちの第一の関心事だ。"],
  "worth": ["This book is worth reading.", "この本は読む価値がある。"],
  "obvious": ["The answer was obvious.", "その答えは明らかだった。"],
  "legal": ["Is this action legal?", "この行為は合法ですか。"],
  "commercial": ["The channel showed a commercial break.", "そのチャンネルではCMが流れた。"],
  "artificial": ["These flowers are artificial.", "これらの花は造花だ。"],
  "chemical": ["The factory uses dangerous chemicals.", "その工場は危険な化学物質を使っている。"],
  "biological": ["Humans have biological needs.", "人間には生物学的な必要がある。"],
  "former": ["My former teacher visited me.", "以前の先生が私を訪ねてきた。"],
  "mobile": ["The library has a mobile clinic.", "その施設には移動式の診療所がある。"],
  "straight": ["Draw a straight line.", "まっすぐな線を引きなさい。"],
  "regular": ["Exercise is part of my regular routine.", "運動は私の普段の習慣の一部だ。"],
  "independent": ["She became financially independent.", "彼女は経済的に自立した。"],
  "overseas": ["He studied overseas last year.", "彼は昨年海外で勉強した。"],
  "unlike": ["Unlike me, she loves sports.", "私と違って、彼女はスポーツが大好きだ。"],
  "via": ["We flew to Paris via Dubai.", "私たちはドバイ経由でパリへ飛んだ。"],
  "whereas": ["He likes tea, whereas I prefer coffee.", "彼はお茶が好きだが、私はコーヒーのほうが好きだ。"],

  "perceive": ["Babies perceive sounds very early.", "赤ちゃんはとても早い段階で音を知覚する。"],
  "fascinate": ["Space always fascinates children.", "宇宙はいつも子どもたちを魅了する。"],
  "bore": ["Long meetings bore me.", "長い会議は私を退屈させる。"],
  "disappoint": ["His answer disappointed me.", "彼の答えは私を失望させた。"],
  "imply": ["Her smile implied agreement.", "彼女の笑顔は賛成をほのめかしていた。"],
  "recommend": ["I recommend this restaurant.", "私はこのレストランを勧める。"],
  "demonstrate": ["The experiment demonstrated the idea clearly.", "その実験はその考えを明確に示した。"],
  "conclude": ["We concluded the meeting early.", "私たちは会議を早めに終えた。"],
  "announce": ["They announced the winner.", "彼らは優勝者を発表した。"],
  "appeal": ["The idea appeals to young people.", "その考えは若者の心に訴える。"],
  "address": ["We must address this problem.", "私たちはこの問題に取り組まなければならない。"],
  "advertise": ["They advertised the sale online.", "彼らはそのセールをネットで宣伝した。"],
  "invite": ["She invited me to dinner.", "彼女は私を夕食に招待した。"],
  "afford": ["We can’t afford a new car.", "私たちは新しい車を買う余裕がない。"],
  "purchase": ["He purchased a train ticket.", "彼は電車の切符を購入した。"],
  "participate": ["Many students participated in the event.", "多くの生徒がその行事に参加した。"],
  "belong": ["This bag belongs to me.", "このかばんは私のものだ。"],
  "conduct": ["Scientists conducted a survey.", "科学者たちは調査を行った。"],
  "behave": ["Children should behave politely.", "子どもは礼儀正しくふるまうべきだ。"],
  "operate": ["Can you operate this machine?", "この機械を操作できますか。"],
  "organize": ["She organized the files neatly.", "彼女は書類をきちんと整理した。"],
  "host": ["Our school hosted the event.", "私たちの学校がその行事を主催した。"],
  "combine": ["Combine flour and sugar.", "小麦粉と砂糖を混ぜなさい。"],
  "deliver": ["They delivered the package this morning.", "彼らは今朝その荷物を配達した。"],
  "locate": ["We located the missing dog.", "私たちはいなくなった犬を見つけた。"],
  "encounter": ["We encountered heavy snow.", "私たちは大雪に遭遇した。"],
  "surround": ["Tall trees surround the house.", "高い木々がその家を囲んでいる。"],
  "explore": ["They explored the island.", "彼らはその島を探検した。"],
  "stick": ["The label won’t stick.", "そのラベルはくっつかない。"],
  "strike": ["The news struck me deeply.", "その知らせは私に強い印象を与えた。"],
  "hurt": ["I hurt my knee.", "私はひざを痛めた。"],
  "bite": ["The dog bit his hand.", "その犬は彼の手にかみついた。"],
  "tear": ["Be careful not to tear the paper.", "紙を破らないように気をつけて。"],
  "aid": ["Foreign countries aided the victims.", "外国が被害者たちを援助した。"],
  "press": ["Press the red button.", "赤いボタンを押してください。"],
  "burn": ["Be careful not to burn the bread.", "パンを焦がさないように気をつけて。"],
  "flow": ["Tears flowed down her face.", "涙が彼女の顔を流れ落ちた。"],
  "preserve": ["We must preserve old buildings.", "私たちは古い建物を保存しなければならない。"],
  "borrow": ["Can I borrow your pen?", "あなたのペンを借りてもいいですか。"],
  "steal": ["Someone stole my bike.", "誰かが私の自転車を盗んだ。"],
  "escape": ["The bird escaped from the cage.", "その鳥はかごから逃げた。"],
  "neighbor": ["Our neighbor is very kind.", "私たちの隣人はとても親切だ。"],
  "household": ["The household uses less water now.", "その家庭は今、使う水を減らしている。"],
  "resident": ["Every resident received a notice.", "すべての住民が通知を受け取った。"],
  "vehicle": ["No vehicles are allowed here.", "ここでは乗り物の進入は禁止されている。"],
  "wheel": ["He turned the wheel left.", "彼はハンドルを左に切った。"],
  "delay": ["Our flight had a long delay.", "私たちの便は大きく遅れた。"],
  "fuel": ["Cars need fuel.", "車には燃料が必要だ。"],
  "pollution": ["Air pollution is a serious problem.", "大気汚染は深刻な問題だ。"],
  "atmosphere": ["The café has a warm atmosphere.", "そのカフェにはあたたかい雰囲気がある。"],
  "electricity": ["The storm cut off electricity.", "嵐で電気が止まった。"],
  "cancer": ["Smoking increases the risk of cancer.", "喫煙はがんの危険を高める。"],
  "plague": ["The plague spread quickly.", "その疫病は急速に広がった。"],
  "threat": ["Climate change is a global threat.", "気候変動は世界的な脅威だ。"],
  "flood": ["The flood damaged many homes.", "洪水は多くの家に被害を与えた。"],
  "earthquake": ["The earthquake woke us up.", "その地震で私たちは目を覚ました。"],
  "disaster": ["The storm became a disaster.", "その嵐は災害になった。"],
  "crisis": ["The country faced an economic crisis.", "その国は経済危機に直面した。"],
  "victim": ["The victim needed urgent care.", "その被害者には緊急の手当てが必要だった。"],
  "wealth": ["Health is greater than wealth.", "健康は富より大切だ。"],
  "fund": ["The school needs more funds.", "その学校にはさらに資金が必要だ。"],
  "capital": ["Tokyo is the capital of Japan.", "東京は日本の首都だ。"],
  "profit": ["The shop made a good profit.", "その店はよい利益を上げた。"],
  "talent": ["She has musical talent.", "彼女には音楽の才能がある。"],
  "capacity": ["This hall has limited capacity.", "このホールには収容人数の限界がある。"],
  "scholar": ["The scholar wrote several books.", "その学者は数冊の本を書いた。"],
  "tradition": ["It is a local tradition.", "それは地域の伝統だ。"],
  "literature": ["He studies English literature.", "彼は英文学を学んでいる。"],
  "lecture": ["The lecture lasted an hour.", "その講義は1時間続いた。"],
  "manner": ["She spoke in a calm manner.", "彼女は落ち着いた話し方をした。"],
  "symbol": ["The dove is a symbol of peace.", "ハトは平和の象徴だ。"],
  "analysis": ["Her analysis was accurate.", "彼女の分析は正確だった。"],
  "version": ["I watched the English version.", "私は英語版を見た。"],
  "perspective": ["Try seeing it from my perspective.", "私の視点からそれを見てみて。"],
  "vision": ["She has a clear vision.", "彼女には明確な展望がある。"],
  "sight": ["The mountain was a beautiful sight.", "その山は美しい景色だった。"],
  "insight": ["The book offers useful insight.", "その本は役立つ洞察を与えてくれる。"],
  "bilingual": ["She is bilingual in English and Japanese.", "彼女は英語と日本語のバイリンガルだ。"],
  "capable": ["He is capable of leading the team.", "彼にはチームを率いる能力がある。"],
  "willing": ["I’m willing to help.", "私は喜んで手伝う。"],
  "eager": ["She was eager to learn.", "彼女は学ぶことに熱心だった。"],
  "amazing": ["We saw an amazing view.", "私たちはすばらしい景色を見た。"],
  "calm": ["Please stay calm.", "落ち着いてください。"],
  "quiet": ["The street was quiet at night.", "その通りは夜静かだった。"],
  "senior": ["Senior staff approved the plan.", "上級職員がその計画を承認した。"],
  "elderly": ["An elderly man crossed the road.", "年配の男性が道路を渡った。"],
  "firm": ["She gave a firm answer.", "彼女はきっぱりとした返事をした。"],
  "severe": ["He had severe back pain.", "彼はひどい腰痛があった。"],
  "tough": ["This exam was tough.", "この試験は難しかった。"],
  "rapid": ["The city saw rapid growth.", "その市は急速な成長を見せた。"],
  "immediate": ["We need immediate action.", "私たちには即時の行動が必要だ。"],
  "vast": ["They crossed a vast desert.", "彼らは広大な砂漠を横断した。"],
  "enormous": ["The building is enormous.", "その建物は巨大だ。"],
  "broad": ["He has broad knowledge.", "彼は幅広い知識を持っている。"],
  "narrow": ["We walked down a narrow street.", "私たちは狭い通りを歩いた。"],
  "tiny": ["A tiny insect landed on my hand.", "小さな昆虫が私の手に止まった。"],
  "efficient": ["She found an efficient method.", "彼女は効率のよい方法を見つけた。"],
  "constant": ["He lives under constant pressure.", "彼は絶え間ないプレッシャーの中で暮らしている。"],
  "nearby": ["There is a nearby park.", "近くに公園がある。"],
  "distant": ["We saw distant mountains.", "私たちは遠くの山々を見た。"]
});
Object.assign(window.EXAMPLE_BANK, {
  "insist": ["He insisted on paying the bill.", "彼は勘定を払うと言い張った。"],
  "intend": ["I intend to study abroad.", "私は留学するつもりだ。"],
  "inspire": ["Her story inspired me.", "彼女の話は私を奮い立たせた。"],
  "emphasize": ["Teachers emphasize clear writing.", "教師はわかりやすい文章を書くことを強調する。"],
  "propose": ["She proposed a new idea.", "彼女は新しい考えを提案した。"],
  "persuade": ["He persuaded me to join.", "彼は私を説得して参加させた。"],
  "convince": ["The evidence convinced us.", "その証拠が私たちを納得させた。"],
  "admit": ["He admitted his mistake.", "彼は自分の間違いを認めた。"],
  "favor": ["I favor this plan.", "私はこの案に賛成だ。"],
  "excuse": ["Please excuse my late reply.", "返事が遅れたことをお許しください。"],
  "interpret": ["People interpret art differently.", "人は芸術をそれぞれ違って解釈する。"],
  "translate": ["Can you translate this sentence?", "この文を翻訳できますか。"],
  "concentrate": ["Please concentrate on your task.", "自分の作業に集中してください。"],
  "criticize": ["Don’t criticize him too harshly.", "彼をあまり厳しく批判しないで。"],
  "blame": ["Don’t blame me for this.", "これを私のせいにしないで。"],
  "oppose": ["Many people oppose the law.", "多くの人がその法律に反対している。"],
  "inform": ["Please inform me of any changes.", "変更があれば知らせてください。"],
  "grant": ["The school granted her a scholarship.", "その学校は彼女に奨学金を与えた。"],
  "obtain": ["He obtained a visa.", "彼はビザを取得した。"],
  "transform": ["The project transformed the town.", "その事業は町を変えた。"],
  "alter": ["We altered the schedule slightly.", "私たちは予定を少し変更した。"],
  "arrange": ["She arranged the flowers beautifully.", "彼女は花を美しく並べた。"],
  "interact": ["Children interact through play.", "子どもは遊びを通して関わり合う。"],
  "handle": ["She handled the problem well.", "彼女はその問題にうまく対処した。"],
  "extend": ["They extended the deadline.", "彼らは締め切りを延ばした。"],
  "settle": ["They settled in Australia.", "彼らはオーストラリアに定住した。"],
  "contribute": ["Everyone can contribute ideas.", "誰でもアイデアを出して貢献できる。"],
  "construct": ["They constructed a new bridge.", "彼らは新しい橋を建設した。"],
  "consist": ["Water consists of hydrogen and oxygen.", "水は水素と酸素から成る。"],
  "suit": ["Blue suits you well.", "青はあなたによく似合う。"],
  "tie": ["The song ties us together.", "その歌は私たちを結びつける。"],
  "differ": ["Our opinions differ.", "私たちの意見は異なる。"],
  "hate": ["I hate waiting in line.", "私は列に並んで待つのが大嫌いだ。"],
  "dislike": ["She dislikes cold weather.", "彼女は寒い天気が嫌いだ。"],
  "disagree": ["We disagree on that point.", "私たちはその点で意見が合わない。"],
  "regret": ["I regret my decision.", "私は自分の決断を後悔している。"],
  "employ": ["The company employs fifty workers.", "その会社は50人の労働者を雇っている。"],
  "hire": ["They hired a new manager.", "彼らは新しい管理者を雇った。"],
  "absorb": ["The book absorbed her completely.", "その本は彼女をすっかり夢中にさせた。"],
  "expose": ["Sunlight exposed the colors.", "日光がその色を明らかにした。"],
  "breathe": ["It’s hard to breathe here.", "ここでは呼吸しにくい。"],
  "root": ["These customs have deep roots.", "これらの慣習には深いルーツがある。"],
  "immigration": ["Immigration changed the city.", "移住はその都市を変えた。"],
  "tribe": ["The tribe lived by the river.", "その部族は川のそばで暮らしていた。"],
  "landscape": ["The mountain landscape was stunning.", "その山の風景は見事だった。"],
  "agriculture": ["Agriculture supports the local economy.", "農業は地域経済を支えている。"],
  "soil": ["The soil is rich here.", "ここの土壌は肥えている。"],
  "mine": ["He works in a coal mine.", "彼は炭鉱で働いている。"],
  "mass": ["The news reached the mass quickly.", "そのニュースは大衆にすぐ広まった。"],
  "quarter": ["A quarter of the class was absent.", "クラスの4分の1が欠席だった。"],
  "era": ["We live in a digital era.", "私たちはデジタル時代に生きている。"],
  "circumstance": ["Under these circumstances, we should wait.", "このような状況では、私たちは待つべきだ。"],
  "phenomenon": ["Rainbows are a natural phenomenon.", "虹は自然現象だ。"],
  "custom": ["Bowing is a common custom here.", "ここではおじぎが一般的な習慣だ。"],
  "religion": ["Religion shapes some traditions.", "宗教はいくつかの伝統を形作っている。"],
  "civilization": ["Ancient civilization left many ruins.", "古代文明は多くの遺跡を残した。"],
  "universe": ["Scientists study the universe.", "科学者たちは宇宙を研究している。"],
  "diversity": ["Diversity makes teams stronger.", "多様性はチームをより強くする。"],
  "trait": ["Patience is a useful trait.", "忍耐は役立つ特性だ。"],
  "review": ["I read a good review online.", "私はネットでよいレビューを読んだ。"],
  "occasion": ["Birthdays are special occasions.", "誕生日は特別な機会だ。"],
  "campaign": ["The campaign encouraged voting.", "その運動は投票を促した。"],
  "board": ["The board approved the plan.", "委員会はその計画を承認した。"],
  "facility": ["The school has modern facilities.", "その学校には近代的な施設がある。"],
  "court": ["The case went to court.", "その事件は法廷に持ち込まれた。"],
  "trial": ["The trial lasted three days.", "その裁判は3日続いた。"],
  "laboratory": ["Students worked in the laboratory.", "生徒たちは研究室で作業した。"],
  "instrument": ["The doctor used a small instrument.", "その医師は小さな器具を使った。"],
  "instruction": ["Please follow the instructions carefully.", "指示に注意深く従ってください。"],
  "document": ["I signed the document.", "私はその書類に署名した。"],
  "target": ["Our target is fifty students.", "私たちの目標は50人の生徒だ。"],
  "outcome": ["The outcome surprised everyone.", "その結果はみんなを驚かせた。"],
  "muscle": ["Exercise builds muscle.", "運動は筋肉をつける。"],
  "wage": ["Workers demand higher wages.", "労働者たちはより高い賃金を求めている。"],
  "gender": ["Gender should not affect pay.", "性別が賃金に影響してはならない。"],
  "confidence": ["Practice builds confidence.", "練習は自信をつける。"],
  "credit": ["She deserves credit for the idea.", "そのアイデアについて彼女は評価されるに値する。"],
  "conscious": ["He was conscious after the accident.", "彼は事故のあと意識があった。"],
  "anxious": ["She felt anxious before the test.", "彼女はテストの前に不安を感じた。"],
  "asleep": ["The baby is asleep.", "赤ちゃんは眠っている。"],
  "alive": ["The plant is still alive.", "その植物はまだ生きている。"],
  "alike": ["The twins look alike.", "その双子はよく似ている。"],
  "excellent": ["She did an excellent job.", "彼女はすばらしい仕事をした。"],
  "odd": ["That seems odd to me.", "それは私には奇妙に思える。"],
  "sensitive": ["He is sensitive to noise.", "彼は音に敏感だ。"],
  "sensible": ["That sounds like a sensible plan.", "それは賢明な計画に聞こえる。"],
  "violent": ["The movie was too violent.", "その映画は暴力的すぎた。"],
  "military": ["He has military experience.", "彼には軍での経験がある。"],
  "nuclear": ["They discussed nuclear energy.", "彼らは原子力エネルギーについて話し合った。"],
  "contemporary": ["I enjoy contemporary art.", "私は現代美術を楽しんでいる。"],
  "elementary": ["He teaches at an elementary school.", "彼は小学校で教えている。"],
  "annual": ["The school holds an annual festival.", "その学校は年1回の祭りを開く。"],
  "chief": ["Safety is our chief concern.", "安全が私たちの第一の関心事だ。"],
  "actual": ["The actual cost was higher.", "実際の費用はもっと高かった。"],
  "virtual": ["We had a virtual meeting.", "私たちはオンライン会議をした。"],
  "numerous": ["The city has numerous parks.", "その市には多くの公園がある。"],
  "multiple": ["She has multiple talents.", "彼女には多くの才能がある。"],
  "widespread": ["The rumor became widespread.", "そのうわさは広く広まった。"],
  "sufficient": ["We have sufficient food.", "私たちには十分な食料がある。"],
  "empty": ["The room was empty.", "その部屋は空だった。"],

  "confirm": ["Please confirm your reservation by email.", "予約をメールで確認してください。"],
  "illustrate": ["This chart illustrates the change clearly.", "この表はその変化を明確に示している。"],
  "spell": ["Can you spell your name?", "あなたの名前のつづりを言えますか。"],
  "bother": ["Sorry to bother you.", "おじゃましてすみません。"],
  "annoy": ["Loud chewing annoys me.", "大きな咀嚼音は私をいらいらさせる。"],
  "disturb": ["Please don’t disturb the baby.", "赤ちゃんのじゃまをしないでください。"],
  "discourage": ["The rain discouraged us.", "雨で私たちはやる気をなくした。"],
  "embarrass": ["His joke embarrassed her.", "彼の冗談は彼女を困らせた。"],
  "frighten": ["Thunder frightened the child.", "雷はその子どもを怖がらせた。"],
  "puzzle": ["The question puzzled me.", "その質問は私を当惑させた。"],
  "upset": ["The news upset her.", "その知らせは彼女を動揺させた。"],
  "stimulate": ["Games stimulate young minds.", "ゲームは子どもの心を刺激する。"],
  "beat": ["Our team beat theirs easily.", "私たちのチームは相手チームに楽に勝った。"],
  "blow": ["A cold wind blew.", "冷たい風が吹いた。"],
  "injure": ["He injured his ankle.", "彼は足首を傷めた。"],
  "cure": ["This medicine cured her cold.", "この薬で彼女の風邪は治った。"],
  "recover": ["She recovered from the illness.", "彼女はその病気から回復した。"],
  "overcome": ["He overcame his fear.", "彼は恐怖を克服した。"],
  "quit": ["She quit her job.", "彼女は仕事を辞めた。"],
  "transfer": ["He transferred to another school.", "彼は別の学校へ移った。"],
  "transport": ["Trucks transport goods across the country.", "トラックは国内に品物を輸送する。"],
  "export": ["Japan exports many cars.", "日本は多くの車を輸出している。"],
  "import": ["The country imports oil.", "その国は石油を輸入している。"],
  "invest": ["They invested in new equipment.", "彼らは新しい設備に投資した。"],
  "investigate": ["Police investigated the accident.", "警察はその事故を調査した。"],
  "manufacture": ["The factory manufactures bicycles.", "その工場は自転車を製造している。"],
  "react": ["She reacted with surprise.", "彼女は驚いて反応した。"],
  "award": ["The school awarded him a prize.", "その学校は彼に賞を授けた。"],
  "ban": ["The city banned smoking here.", "その市はここでの喫煙を禁止した。"],
  "prohibit": ["The rules prohibit phone use.", "その規則は携帯電話の使用を禁止している。"],
  "forbid": ["My parents forbid late nights.", "私の親は夜更かしを禁じている。"],
  "abandon": ["They abandoned the old house.", "彼らはその古い家を捨てた。"],
  "freeze": ["Water freezes at zero degrees.", "水は0度で凍る。"],
  "lift": ["Can you lift this box?", "この箱を持ち上げられますか。"],
  "hang": ["Hang your coat here.", "ここにコートをかけてください。"],
  "shake": ["He shook my hand.", "彼は私と握手した。"],
  "stretch": ["Stretch your legs first.", "まず足を伸ばしてください。"],
  "lay": ["She laid the book down.", "彼女はその本を置いた。"],
  "stare": ["Don’t stare at people.", "人をじろじろ見てはいけない。"],
  "gaze": ["She gazed at the stars.", "彼女は星を見つめた。"],
  "capture": ["The photo captured the moment.", "その写真はその瞬間をとらえた。"],
  "breed": ["Farmers breed cows here.", "ここでは農家が牛を飼育している。"],
  "mammal": ["A dolphin is a mammal.", "イルカは哺乳類だ。"],
  "ape": ["The zoo has an ape.", "その動物園には類人猿がいる。"],
  "insect": ["An insect landed on my arm.", "昆虫が私の腕に止まった。"],
  "infant": ["The infant was sleeping peacefully.", "その乳児は静かに眠っていた。"],
  "organ": ["The heart is a vital organ.", "心臓は重要な臓器だ。"],
  "web": ["I found it on the web.", "私はそれをウェブで見つけた。"],
  "fossil": ["They found a dinosaur fossil.", "彼らは恐竜の化石を見つけた。"],
  "battle": ["The battle lasted for hours.", "その戦闘は何時間も続いた。"],
  "enemy": ["The soldiers fought the enemy.", "兵士たちは敵と戦った。"],
  "weapon": ["Police found a weapon.", "警察は武器を見つけた。"],
  "arm": ["He hurt his arm.", "彼は腕をけがした。"],
  "army": ["The army entered the city.", "陸軍はその市に入った。"],
  "navy": ["He joined the navy.", "彼は海軍に入った。"],
  "border": ["They crossed the border safely.", "彼らは無事に国境を越えた。"],
  "barrier": ["Language can be a barrier.", "言語は障壁になりうる。"],
  "philosophy": ["She studies philosophy at university.", "彼女は大学で哲学を学んでいる。"],
  "psychology": ["He is interested in psychology.", "彼は心理学に興味がある。"],
  "alarm": ["My alarm rang at six.", "私の目覚ましは6時に鳴った。"],
  "harm": ["Smoking causes serious harm.", "喫煙は深刻な害をもたらす。"],
  "depression": ["He suffered from depression.", "彼はうつ病に苦しんだ。"],
  "disadvantage": ["Cost is the main disadvantage.", "費用が主な不利な点だ。"],
  "shortage": ["The town faced a water shortage.", "その町は水不足に直面した。"],
  "stock": ["The store has enough stock.", "その店には十分な在庫がある。"],
  "loan": ["He got a bank loan.", "彼は銀行ローンを受けた。"],
  "budget": ["We need a larger budget.", "私たちにはもっと大きな予算が必要だ。"],
  "innovation": ["Innovation drives economic growth.", "革新は経済成長を促す。"],
  "union": ["The workers joined the union.", "労働者たちは組合に入った。"],
  "unit": ["The lesson has five units.", "その課には5つの単元がある。"],
  "material": ["This bag is made of strong material.", "このバッグは丈夫な素材でできている。"],
  "substance": ["The bottle contained a strange substance.", "そのびんには奇妙な物質が入っていた。"],
  "stuff": ["Please move your stuff.", "自分の持ち物を移動してください。"],
  "proportion": ["A large proportion agreed.", "多くの割合の人が賛成した。"],
  "edge": ["Be careful near the edge.", "端の近くでは気をつけて。"],
  "code": ["Enter the security code.", "暗証コードを入力してください。"],
  "mystery": ["The case remains a mystery.", "その事件は依然としてなぞのままだ。"],
  "curious": ["Children are naturally curious.", "子どもは生まれつき好奇心が強い。"],
  "strict": ["Our teacher is strict but fair.", "私たちの先生は厳しいが公正だ。"],
  "frank": ["She gave a frank answer.", "彼女は率直な答えをした。"],
  "polite": ["Please be polite to guests.", "客には礼儀正しくしなさい。"],
  "aggressive": ["His aggressive attitude caused trouble.", "彼の攻撃的な態度が問題を引き起こした。"],
  "accurate": ["The report was accurate.", "その報告は正確だった。"],
  "exact": ["What is the exact time?", "正確な時刻は何時ですか。"],
  "proper": ["Wear proper shoes for hiking.", "ハイキングには適切な靴を履きなさい。"],
  "brief": ["We had a brief chat.", "私たちは短く話した。"],
  "extraordinary": ["She showed extraordinary talent.", "彼女は並外れた才能を見せた。"],
  "flexible": ["My schedule is flexible today.", "今日は私の予定に融通がきく。"],
  "pleasant": ["We had a pleasant evening.", "私たちは楽しい夕べを過ごした。"],
  "comfortable": ["This chair is comfortable.", "この椅子は座り心地がよい。"],
  "stable": ["Their relationship seems stable.", "彼らの関係は安定しているようだ。"],
  "thick": ["The book is very thick.", "その本はとても厚い。"],
  "thin": ["He looked thin after the illness.", "彼は病気のあとやせて見えた。"],
  "abstract": ["The idea is too abstract.", "その考えは抽象的すぎる。"],
  "concrete": ["We need concrete examples.", "私たちには具体例が必要だ。"],
  "absolute": ["I have absolute trust in her.", "私は彼女を絶対的に信頼している。"],
  "prime": ["Safety is our prime concern.", "安全が私たちの最重要事項だ。"],
  "vital": ["Water is vital for life.", "水は生命にとって極めて重要だ。"],
  "contrary": ["His actions were contrary to the rules.", "彼の行動は規則に反していた。"],
  "regardless": ["We went out regardless of the rain.", "雨にもかかわらず私たちは出かけた。"],

  "permit": ["The school permits casual clothes on Fridays.", "その学校は金曜日に私服を認めている。"],
  "suspect": ["I suspect he already knows.", "彼はもう知っているのではないかと思う。"],
  "pursue": ["She wants to pursue music.", "彼女は音楽の道を追求したいと思っている。"],
  "pretend": ["He pretended to be asleep.", "彼は眠っているふりをした。"],
  "calculate": ["Can you calculate the total cost?", "合計費用を計算できますか。"],
  "guarantee": ["This ticket guarantees your seat.", "このチケットはあなたの席を保証する。"],
  "acknowledge": ["He acknowledged my message.", "彼は私のメッセージを確認した。"],
  "impress": ["Her speech impressed everyone.", "彼女のスピーチはみんなに感銘を与えた。"],
  "urge": ["Doctors urge people to exercise.", "医師たちは人々に運動するよう強く勧めている。"],
  "convey": ["His eyes conveyed sadness.", "彼の目は悲しみを伝えていた。"],
  "celebrate": ["We celebrated her birthday.", "私たちは彼女の誕生日を祝った。"],
  "admire": ["I admire her courage.", "私は彼女の勇気に感心している。"],
  "devote": ["She devoted her life to art.", "彼女は一生を芸術にささげた。"],
  "dominate": ["One team dominated the match.", "一方のチームがその試合を支配した。"],
  "eliminate": ["We must eliminate waste.", "私たちは無駄を取り除かなければならない。"],
  "restrict": ["The rule restricts access.", "その規則は利用を制限している。"],
  "isolate": ["The disease isolated him from others.", "その病気で彼は他人から切り離された。"],
  "endanger": ["Pollution endangers marine life.", "汚染は海の生き物を危険にさらしている。"],
  "secure": ["We secured enough seats.", "私たちは十分な席を確保した。"],
  "reserve": ["I reserved a table online.", "私はネットでテーブルを予約した。"],
  "possess": ["She possesses great patience.", "彼女は大きな忍耐力を持っている。"],
  "launch": ["They launched a new product.", "彼らは新製品を発売した。"],
  "detect": ["The test detected a problem.", "その検査で問題が見つかった。"],
  "reverse": ["The car reversed slowly.", "その車はゆっくりバックした。"],
  "convert": ["They converted the room into an office.", "彼らはその部屋を事務所に変えた。"],
  "hurry": ["We hurried to the station.", "私たちは急いで駅へ向かった。"],
  "rush": ["Don’t rush your answer.", "急いで答えないで。"],
  "roll": ["The ball rolled away.", "ボールは転がっていった。"],
  "crash": ["The car crashed into a wall.", "その車は壁に衝突した。"],
  "bury": ["They buried the dog in the yard.", "彼らはその犬を庭に埋めた。"],
  "dig": ["He dug a deep hole.", "彼は深い穴を掘った。"],
  "attach": ["Please attach your photo.", "写真を添付してください。"],
  "melt": ["Ice melts quickly in summer.", "氷は夏にすぐ溶ける。"],
  "accompany": ["She accompanied me to the hospital.", "彼女は私に付き添って病院へ行ってくれた。"],
  "assist": ["Two nurses assisted the doctor.", "2人の看護師が医師を手伝った。"],
  "cope": ["She coped with stress well.", "彼女はストレスにうまく対処した。"],
  "lend": ["Can you lend me some money?", "少しお金を貸してくれますか。"],
  "rent": ["We rented a small apartment.", "私たちは小さなアパートを借りた。"],
  "owe": ["I owe you ten dollars.", "私はあなたに10ドル借りている。"],
  "apologize": ["He apologized for being late.", "彼は遅れたことを謝った。"],
  "forgive": ["Please forgive my mistake.", "私の間違いを許してください。"],
  "tongue": ["My tongue still hurts.", "私の舌はまだ痛い。"],
  "dialect": ["They speak a local dialect.", "彼らはその土地の方言を話す。"],
  "accent": ["She has a strong accent.", "彼女には強いなまりがある。"],
  "colony": ["The ants built a colony.", "アリは巣を作った。"],
  "grain": ["Rice is a basic grain.", "米は基本的な穀物だ。"],
  "harvest": ["Farmers began the rice harvest.", "農家の人たちは稲の収穫を始めた。"],
  "ingredient": ["Salt is the main ingredient.", "塩が主な材料だ。"],
  "portion": ["She ate a small portion.", "彼女は少量食べた。"],
  "hunger": ["Hunger remains a global problem.", "飢えはいまだに世界的な問題だ。"],
  "obesity": ["Obesity can cause health problems.", "肥満は健康問題を引き起こすことがある。"],
  "burden": ["The debt became a burden.", "その借金は重荷になった。"],
  "emergency": ["Call for help in an emergency.", "緊急時には助けを呼びなさい。"],
  "debt": ["He fell into debt.", "彼は借金を抱えるようになった。"],
  "contract": ["I signed the contract yesterday.", "私は昨日その契約に署名した。"],
  "client": ["The lawyer met her client.", "その弁護士は依頼人に会った。"],
  "therapy": ["Music therapy helped him relax.", "音楽療法が彼を落ち着かせた。"],
  "physician": ["The physician examined my throat.", "その医師は私ののどを診察した。"],
  "democracy": ["Democracy needs fair elections.", "民主主義には公正な選挙が必要だ。"],
  "election": ["The election will be held soon.", "その選挙はまもなく行われる。"],
  "vote": ["Many young people voted.", "多くの若者が投票した。"],
  "candidate": ["She is the best candidate.", "彼女が最良の候補者だ。"],
  "minister": ["The minister gave a speech.", "その大臣は演説した。"],
  "conference": ["They attended an international conference.", "彼らは国際会議に出席した。"],
  "ceremony": ["The ceremony starts at ten.", "式典は10時に始まる。"],
  "institution": ["The university is a respected institution.", "その大学は評価の高い機関だ。"],
  "corporation": ["He works for a large corporation.", "彼は大企業で働いている。"],
  "cooperation": ["Success needs close cooperation.", "成功には緊密な協力が必要だ。"],
  "authority": ["Local authorities closed the road.", "地元当局はその道路を閉鎖した。"],
  "theme": ["Love is the main theme.", "愛が主なテーマだ。"],
  "notion": ["I rejected that notion.", "私はその考えを退けた。"],
  "hypothesis": ["The data supports his hypothesis.", "そのデータは彼の仮説を支持している。"],
  "discipline": ["Good discipline helps students learn.", "よい規律は生徒の学習を助ける。"],
  "route": ["This route is faster.", "この道順のほうが速い。"],
  "routine": ["Exercise is part of my routine.", "運動は私の日課の一部だ。"],
  "destination": ["Paris was our final destination.", "パリが私たちの最終目的地だった。"],
  "domestic": ["Domestic flights were delayed.", "国内線は遅れていた。"],
  "ethnic": ["The city has many ethnic groups.", "その市には多くの民族集団がある。"],
  "alien": ["Their customs felt alien to me.", "彼らの習慣は私には異質に感じられた。"],
  "visible": ["The moon was clearly visible.", "月がはっきり見えた。"],
  "verbal": ["We reached a verbal agreement.", "私たちは口頭で合意した。"],
  "fundamental": ["Trust is fundamental in friendship.", "友情において信頼は基本だ。"],
  "conventional": ["They chose a conventional method.", "彼らは従来の方法を選んだ。"],
  "relevant": ["Please give relevant details.", "関係のある詳細を述べてください。"],
  "rational": ["Her choice was rational.", "彼女の選択は合理的だった。"],
  "precise": ["Please give a precise answer.", "正確な答えをください。"],
  "principal": ["Safety is the principal issue.", "安全が主要な問題だ。"],
  "crucial": ["Good sleep is crucial for health.", "よい睡眠は健康にとって重要だ。"],
  "permanent": ["The damage was permanent.", "その損傷は永久的だった。"],
  "intense": ["He felt intense pressure.", "彼は強い重圧を感じた。"],
  "equivalent": ["One dollar is not equivalent to one euro.", "1ドルは1ユーロに相当しない。"],
  "frequent": ["We had frequent meetings.", "私たちは頻繁に会議をした。"],
  "sudden": ["There was a sudden change.", "突然の変化があった。"],
  "temporary": ["They found temporary housing.", "彼らは一時的な住まいを見つけた。"],
  "internal": ["The company made internal changes.", "その会社は内部改革を行った。"],
  "external": ["The building has external stairs.", "その建物には外階段がある。"],
  "distinct": ["The two sounds are distinct.", "その2つの音は明確に異なる。"],
  "extinct": ["Dinosaurs are extinct now.", "恐竜は今では絶滅している。"],
  "exhausted": ["I felt exhausted after work.", "仕事のあと私は疲れ果てていた。"],
  "evil": ["The story has an evil king.", "その物語には邪悪な王が出てくる。"]
});
Object.assign(window.EXAMPLE_BANK, {
  "greet": ["She greeted me with a smile.", "彼女は笑顔で私にあいさつした。"],
  "chat": ["We chatted after class.", "私たちは授業のあとおしゃべりした。"],
  "remark": ["He remarked on the weather.", "彼は天気について述べた。"],
  "command": ["The officer commanded them to stop.", "その士官は彼らに止まるよう命じた。"],
  "utter": ["She uttered no word.", "彼女はひと言も発しなかった。"],
  "declare": ["They declared the result official.", "彼らはその結果を公式なものと宣言した。"],
  "pronounce": ["Can you pronounce this word?", "この単語を発音できますか。"],
  "correspond": ["The two numbers correspond exactly.", "その2つの数字はぴったり一致する。"],
  "imitate": ["Children often imitate adults.", "子どもはよく大人のまねをする。"],
  "resemble": ["You resemble your mother.", "あなたはお母さんに似ている。"],
  "exhibit": ["The museum exhibits local art.", "その博物館は地元の美術作品を展示している。"],
  "distribute": ["They distributed food to families.", "彼らは家庭に食料を配った。"],
  "attribute": ["Many people attribute success to luck.", "多くの人は成功を運のおかげだと考える。"],
  "evaluate": ["Teachers evaluate students fairly.", "教師は生徒を公平に評価する。"],
  "assess": ["Doctors assessed his condition.", "医師たちは彼の状態を評価した。"],
  "deserve": ["She deserves praise.", "彼女は賞賛に値する。"],
  "weigh": ["The baby weighs three kilos.", "その赤ちゃんの体重は3キロある。"],
  "strengthen": ["Exercise strengthens your muscles.", "運動は筋肉を強くする。"],
  "weaken": ["Illness weakened his body.", "病気で彼の体は弱った。"],
  "approve": ["I approve of your plan.", "私はあなたの計画に賛成だ。"],
  "assign": ["The teacher assigned homework.", "先生は宿題を課した。"],
  "sustain": ["Plants need water to sustain growth.", "植物は成長を維持するのに水が必要だ。"],
  "accomplish": ["She accomplished her goal.", "彼女は目標を成し遂げた。"],
  "relieve": ["This medicine relieved my pain.", "この薬は私の痛みを和らげた。"],
  "frustrate": ["Delays frustrate passengers.", "遅れは乗客をいらだたせる。"],
  "scare": ["Loud noises scare babies.", "大きな音は赤ちゃんを怖がらせる。"],
  "resist": ["He resisted the temptation.", "彼は誘惑に負けなかった。"],
  "protest": ["Students protested against the rule.", "生徒たちはその規則に抗議した。"],
  "shut": ["Please shut the door.", "ドアを閉めてください。"],
  "defeat": ["Our team defeated the champions.", "私たちのチームは優勝チームを破った。"],
  "neglect": ["Don’t neglect your health.", "健康をおろそかにしてはいけない。"],
  "retire": ["My father retired last year.", "私の父は昨年引退した。"],
  "reform": ["The city reformed its school system.", "その市は学校制度を改革した。"],
  "collapse": ["The old bridge collapsed.", "古い橋が崩れた。"],
  "ruin": ["Rain ruined our picnic.", "雨で私たちのピクニックは台無しになった。"],
  "sink": ["The boat sank quickly.", "その船はすぐに沈んだ。"],
  "pile": ["She piled books on the desk.", "彼女は机の上に本を積み重ねた。"],
  "derive": ["Many words derive from Latin.", "多くの語はラテン語に由来する。"],
  "yield": ["This farm yields good rice.", "この農場はよい米を産出する。"],
  "occupy": ["The sofa occupies too much space.", "そのソファは場所を取りすぎる。"],
  "wrap": ["She wrapped the gift carefully.", "彼女はその贈り物をていねいに包んだ。"],
  "embrace": ["She embraced her daughter warmly.", "彼女は娘をあたたかく抱きしめた。"],
  "length": ["What is the length of the table?", "そのテーブルの長さはどれくらいですか。"],
  "height": ["The height of the wall surprised me.", "その壁の高さに私は驚いた。"],
  "volume": ["Please lower the volume.", "音量を下げてください。"],
  "sum": ["He paid a large sum.", "彼は大金を支払った。"],
  "frame": ["The photo is in a silver frame.", "その写真は銀色の額縁に入っている。"],
  "boundary": ["The fence marks the boundary.", "そのフェンスが境界を示している。"],
  "district": ["He lives in my school district.", "彼は私の学区に住んでいる。"],
  "territory": ["Wolves protect their territory.", "オオカミは自分たちの縄張りを守る。"],
  "square": ["Draw a square here.", "ここに正方形を描きなさい。"],
  "empire": ["The empire ruled many lands.", "その帝国は多くの土地を支配した。"],
  "heritage": ["The town protects its cultural heritage.", "その町は文化遺産を守っている。"],
  "fee": ["There is no entry fee.", "入場料はかからない。"],
  "discount": ["Students get a discount.", "学生には割引がある。"],
  "charity": ["She gave money to charity.", "彼女は慈善事業にお金を寄付した。"],
  "mission": ["Their mission was clear.", "彼らの使命は明確だった。"],
  "profession": ["Teaching is a rewarding profession.", "教職はやりがいのある職業だ。"],
  "slave": ["The story is about a slave.", "その物語は奴隷についての話だ。"],
  "witness": ["A witness saw the accident.", "目撃者がその事故を見た。"],
  "incident": ["The incident caused concern.", "その出来事は不安を引き起こした。"],
  "insurance": ["I need car insurance.", "私は自動車保険が必要だ。"],
  "welfare": ["The program supports child welfare.", "その制度は児童福祉を支えている。"],
  "treasure": ["The box held hidden treasure.", "その箱には隠された宝が入っていた。"],
  "leisure": ["Reading is my leisure activity.", "読書は私の余暇の過ごし方だ。"],
  "priority": ["Safety is our top priority.", "安全が私たちの最優先事項だ。"],
  "reputation": ["The restaurant has a good reputation.", "そのレストランは評判がよい。"],
  "honor": ["It was an honor to meet her.", "彼女に会えて光栄だった。"],
  "statue": ["A statue stood in the park.", "公園に像が立っていた。"],
  "architecture": ["I love old architecture.", "私は古い建築が好きだ。"],
  "logic": ["Your argument lacks logic.", "あなたの主張には論理が欠けている。"],
  "mechanism": ["Nobody understood the mechanism fully.", "その仕組みを完全に理解した人はいなかった。"],
  "clue": ["Police found an important clue.", "警察は重要な手がかりを見つけた。"],
  "means": ["Money is not the only means.", "お金だけが手段ではない。"],
  "trap": ["The mouse escaped the trap.", "ネズミはわなから逃げた。"],
  "trick": ["He played a clever trick.", "彼はうまい策略を使った。"],
  "guard": ["A guard checked our bags.", "警備員が私たちのかばんを調べた。"],
  "innocent": ["He was found innocent.", "彼は無罪だとされた。"],
  "guilty": ["She felt guilty afterward.", "彼女はそのあと罪悪感を抱いた。"],
  "rude": ["It is rude to interrupt.", "さえぎるのは失礼だ。"],
  "shy": ["He is shy with strangers.", "彼は見知らぬ人の前では内気だ。"],
  "liberal": ["Her parents are quite liberal.", "彼女の親はかなり寛大だ。"],
  "stupid": ["That was a stupid mistake.", "それはばかな間違いだった。"],
  "reluctant": ["She was reluctant to speak.", "彼女は話すのに気が進まなかった。"],
  "generous": ["He is generous with his time.", "彼は自分の時間を惜しみなく使ってくれる。"],
  "modest": ["She gave a modest reply.", "彼女は控えめな返答をした。"],
  "lonely": ["I felt lonely after moving.", "引っ越したあと私は寂しかった。"],
  "pure": ["The water looks pure.", "その水は純粋に見える。"],
  "grand": ["They stayed in a grand hotel.", "彼らは豪華なホテルに泊まった。"],
  "adequate": ["We have adequate supplies.", "私たちには十分な物資がある。"],
  "apparent": ["His fear was apparent.", "彼の恐れは明らかだった。"],
  "classic": ["This is a classic novel.", "これは古典的な小説だ。"],
  "remote": ["They live in a remote village.", "彼らは遠く離れた村に住んでいる。"],
  "solid": ["The table feels solid.", "その机はしっかりしている。"],
  "raw": ["She ate raw fish.", "彼女は生の魚を食べた。"],
  "plain": ["Please use plain language.", "わかりやすい言葉を使ってください。"],
  "primitive": ["They used primitive tools.", "彼らは原始的な道具を使った。"],
  "steady": ["She made steady progress.", "彼女は着実に進歩した。"],
  "slight": ["I felt a slight pain.", "私はわずかな痛みを感じた。"],
  "subtle": ["The difference is subtle.", "その違いは微妙だ。"],

  "delight": ["The gift delighted her.", "その贈り物は彼女を大喜びさせた。"],
  "entertain": ["The clown entertained the children.", "そのピエロは子どもたちを楽しませた。"],
  "fulfill": ["Hard work fulfilled his dream.", "努力によって彼の夢はかなえられた。"],
  "cheer": ["Her words cheered me up.", "彼女の言葉で私は元気づけられた。"],
  "amuse": ["The joke amused everyone.", "その冗談はみんなを笑わせた。"],
  "anticipate": ["We anticipated heavy traffic.", "私たちはひどい渋滞を予期していた。"],
  "confront": ["We must confront the problem.", "私たちはその問題に立ち向かわなければならない。"],
  "undergo": ["He underwent surgery last week.", "彼は先週手術を受けた。"],
  "exceed": ["Costs exceeded our budget.", "費用は私たちの予算を超えた。"],
  "overwhelm": ["The amount of work overwhelmed me.", "その仕事量に私はまいってしまった。"],
  "shoot": ["The hunter shot a deer.", "その猟師は鹿を撃った。"],
  "murder": ["The film showed a murder.", "その映画には殺人の場面があった。"],
  "rob": ["Two men robbed the bank.", "2人の男が銀行を襲った。"],
  "deprive": ["The noise deprived me of sleep.", "その騒音で私は眠れなかった。"],
  "rid": ["This medicine rid me of pain.", "この薬で私は痛みから解放された。"],
  "interrupt": ["Please don’t interrupt me.", "話をさえぎらないでください。"],
  "interfere": ["Don’t interfere with their plans.", "彼らの計画のじゃまをしないで。"],
  "bully": ["Some students bullied him online.", "何人かの生徒がネット上で彼をいじめた。"],
  "defend": ["Soldiers defended the town.", "兵士たちはその町を守った。"],
  "rescue": ["Firefighters rescued the child.", "消防士たちはその子どもを救助した。"],
  "accuse": ["She accused him of lying.", "彼女は彼がうそをついたと非難した。"],
  "sue": ["They sued the company.", "彼らはその会社を訴えた。"],
  "wander": ["We wandered around the city.", "私たちは町をぶらぶら歩き回った。"],
  "chase": ["The dog chased the cat.", "その犬は猫を追いかけた。"],
  "arrest": ["Police arrested the suspect.", "警察は容疑者を逮捕した。"],
  "submit": ["Please submit your report today.", "今日中にレポートを提出してください。"],
  "punish": ["Teachers should not punish unfairly.", "教師は不公平に罰してはならない。"],
  "resolve": ["We resolved the conflict peacefully.", "私たちはその対立を平和的に解決した。"],
  "justify": ["Nothing can justify violence.", "何ものも暴力を正当化できない。"],
  "restore": ["They restored the old temple.", "彼らは古い寺を修復した。"],
  "modify": ["We modified the plan slightly.", "私たちはその計画を少し修正した。"],
  "impose": ["The school imposed strict rules.", "その学校は厳しい規則を課した。"],
  "compose": ["Ten players compose the team.", "10人の選手がそのチームを構成している。"],
  "classify": ["We classified the books by topic.", "私たちは本を話題ごとに分類した。"],
  "substitute": ["You can substitute honey for sugar.", "砂糖の代わりにハチミツを使えます。"],
  "shrink": ["My sweater shrank in the wash.", "私のセーターは洗って縮んだ。"],
  "lean": ["He leaned against the wall.", "彼は壁にもたれかかった。"],
  "fold": ["Please fold the paper in half.", "その紙を半分に折ってください。"],
  "load": ["They loaded the truck quickly.", "彼らはすばやくトラックに積み込んだ。"],
  "pour": ["She poured tea into the cup.", "彼女はカップにお茶を注いだ。"],
  "float": ["The boat floated on the lake.", "そのボートは湖に浮かんでいた。"],
  "shine": ["Stars shone brightly.", "星が明るく輝いていた。"],
  "editor": ["The editor checked my article.", "編集者が私の記事を確認した。"],
  "poetry": ["She enjoys reading poetry.", "彼女は詩を読むのを楽しんでいる。"],
  "usage": ["Check the word’s usage here.", "ここでその語の使い方を確認しなさい。"],
  "sector": ["Tourism is a growing sector.", "観光業は成長している分野だ。"],
  "span": ["The bridge has a long span.", "その橋は長い支間を持っている。"],
  "literacy": ["The program improved literacy rates.", "その計画で読み書き能力の割合が向上した。"],
  "symptom": ["Fever is a common symptom.", "熱はよくある症状だ。"],
  "phase": ["We entered a new phase.", "私たちは新しい段階に入った。"],
  "surgery": ["She had heart surgery.", "彼女は心臓の手術を受けた。"],
  "virus": ["The virus spread rapidly.", "そのウイルスは急速に広がった。"],
  "poison": ["The bottle contained poison.", "そのびんには毒が入っていた。"],
  "protein": ["Eggs are rich in protein.", "卵はたんぱく質が豊富だ。"],
  "liquid": ["Water is a clear liquid.", "水は透明な液体だ。"],
  "oxygen": ["Plants produce oxygen.", "植物は酸素を生み出す。"],
  "globe": ["News spread across the globe.", "そのニュースは世界中に広まった。"],
  "pole": ["The North Pole is icy.", "北極は氷に覆われている。"],
  "valley": ["A river runs through the valley.", "谷を川が流れている。"],
  "conservation": ["The group supports forest conservation.", "その団体は森林保護を支援している。"],
  "channel": ["We changed the TV channel.", "私たちはテレビのチャンネルを変えた。"],
  "glacier": ["The glacier is melting fast.", "その氷河は急速に溶けている。"],
  "pioneer": ["She was a pioneer in science.", "彼女は科学分野の先駆者だった。"],
  "prospect": ["Job prospects look good.", "仕事の見込みはよさそうだ。"],
  "enthusiasm": ["The students showed real enthusiasm.", "生徒たちは本当の熱意を見せた。"],
  "passion": ["She has a passion for music.", "彼女は音楽に情熱を持っている。"],
  "fortune": ["He made a fortune in business.", "彼は商売で財産を築いた。"],
  "obstacle": ["Lack of time was an obstacle.", "時間不足が障害だった。"],
  "prejudice": ["We must fight prejudice.", "私たちは偏見と戦わなければならない。"],
  "justice": ["They demanded justice.", "彼らは正義を求めた。"],
  "opponent": ["He respected his opponent.", "彼は対戦相手を尊重した。"],
  "sacrifice": ["Success often requires sacrifice.", "成功にはしばしば犠牲が必要だ。"],
  "fault": ["The accident was my fault.", "その事故は私の責任だった。"],
  "prison": ["The criminal was sent to prison.", "その犯罪者は刑務所へ送られた。"],
  "shelter": ["We took shelter from the rain.", "私たちは雨宿りした。"],
  "committee": ["The committee met today.", "委員会は今日開かれた。"],
  "ritual": ["Morning tea is his ritual.", "朝のお茶は彼の日課のような儀式だ。"],
  "mature": ["She is mature for her age.", "彼女は年齢のわりに大人びている。"],
  "moderate": ["Exercise at a moderate pace.", "適度なペースで運動しなさい。"],
  "neutral": ["Try to stay neutral.", "中立を保つようにしなさい。"],
  "optimistic": ["She feels optimistic about the future.", "彼女は将来について楽観的だ。"],
  "pessimistic": ["He is pessimistic about the result.", "彼は結果について悲観的だ。"],
  "radical": ["They proposed radical changes.", "彼らは根本的な変化を提案した。"],
  "rough": ["The road is rough here.", "ここの道はでこぼこしている。"],
  "smooth": ["Her skin feels smooth.", "彼女の肌はなめらかだ。"],
  "fluent": ["She speaks fluent English.", "彼女は流ちょうな英語を話す。"],
  "casual": ["He wore casual clothes.", "彼は普段着を着ていた。"],
  "instant": ["We got an instant reply.", "私たちはすぐに返事をもらった。"],
  "incredible": ["That was an incredible performance.", "それは信じられないほどすばらしい演技だった。"],
  "genuine": ["Her smile was genuine.", "彼女の笑顔は本物だった。"],
  "precious": ["Time is precious.", "時間は貴重だ。"],
  "prominent": ["She is a prominent scientist.", "彼女は著名な科学者だ。"],
  "blind": ["The blind man crossed carefully.", "その目の不自由な男性は注意深く渡った。"],
  "deaf": ["The boy was born deaf.", "その少年は耳が聞こえない状態で生まれた。"],
  "harsh": ["Winter is harsh there.", "そこでは冬が厳しい。"],
  "prompt": ["Thank you for your prompt reply.", "早いご返事をありがとうございます。"],
  "inevitable": ["Change is inevitable.", "変化は避けられない。"],
  "marine": ["We studied marine animals.", "私たちは海の動物について学んだ。"],
  "tropical": ["They visited a tropical island.", "彼らは熱帯の島を訪れた。"],
  "Arctic": ["Polar bears live in the Arctic.", "ホッキョクグマは北極に住んでいる。"],

  "forecast": ["The forecast says rain tomorrow.", "天気予報では明日は雨だ。"],
  "speculate": ["Experts speculated about the cause.", "専門家たちはその原因について推測した。"],
  "bet": ["I bet he forgot.", "彼は忘れたに違いないと思う。"],
  "quote": ["She quoted her teacher.", "彼女は先生の言葉を引用した。"],
  "consult": ["You should consult a doctor.", "医者に相談すべきだ。"],
  "dispute": ["They disputed the decision.", "彼らはその決定に異議を唱えた。"],
  "accumulate": ["Dust accumulated on the shelf.", "ほこりが棚に積もった。"],
  "grasp": ["He finally grasped the idea.", "彼はついにその考えを理解した。"],
  "grip": ["She gripped my hand tightly.", "彼女は私の手をしっかり握った。"],
  "seize": ["Police seized the drugs.", "警察はその薬物を押収した。"],
  "comprehend": ["I couldn’t comprehend his answer.", "私は彼の答えを理解できなかった。"],
  "constitute": ["Women constitute half the class.", "女性がクラスの半分を占めている。"],
  "reinforce": ["Praise reinforces good habits.", "ほめることはよい習慣を強化する。"],
  "resort": ["They resorted to violence.", "彼らは暴力に訴えた。"],
  "donate": ["We donated old clothes.", "私たちは古着を寄付した。"],
  "obey": ["Children should obey traffic rules.", "子どもは交通ルールに従うべきだ。"],
  "dedicate": ["She dedicated her life to teaching.", "彼女は一生を教育にささげた。"],
  "transmit": ["Radios transmit signals.", "ラジオは信号を送る。"],
  "equip": ["The school equipped each room with computers.", "その学校は各教室にコンピューターを備えつけた。"],
  "bind": ["The rope bound his hands.", "ロープが彼の手をしばっていた。"],
  "pose": ["The change poses a risk.", "その変化は危険をもたらす。"],
  "pause": ["He paused for a moment.", "彼は少しの間立ち止まった。"],
  "hesitate": ["Don’t hesitate to ask questions.", "遠慮せず質問してください。"],
  "split": ["We split the bill.", "私たちは勘定を割り勘にした。"],
  "bend": ["Bend your knees slightly.", "ひざを少し曲げてください。"],
  "tap": ["He tapped me on the shoulder.", "彼は私の肩を軽くたたいた。"],
  "boil": ["Boil the water first.", "まず水を沸かしてください。"],
  "bow": ["The actors bowed to the audience.", "俳優たちは観客におじぎをした。"],
  "conceal": ["He concealed his feelings.", "彼は気持ちを隠した。"],
  "dispose": ["Please dispose of the trash properly.", "ごみは適切に処分してください。"],
  "cheat": ["He cheated on the test.", "彼はテストでカンニングした。"],
  "distract": ["Noise distracts me easily.", "騒音があると私はすぐ気が散る。"],
  "exclude": ["The price excludes tax.", "その価格には税が含まれていない。"],
  "astonish": ["Her courage astonished us.", "彼女の勇気に私たちは驚いた。"],
  "thrill": ["The game thrilled the crowd.", "その試合は観衆をわくわくさせた。"],
  "leap": ["The cat leaped onto the table.", "その猫はテーブルの上に飛び乗った。"],
  "postpone": ["They postponed the meeting.", "彼らは会議を延期した。"],
  "dismiss": ["The company dismissed two workers.", "その会社は2人の労働者を解雇した。"],
  "resign": ["He resigned from his job.", "彼は仕事を辞めた。"],
  "withdraw": ["She withdrew some cash.", "彼女は現金を少し引き出した。"],
  "fade": ["The colors faded in the sun.", "その色は日に当たってあせた。"],
  "vanish": ["The rabbit vanished suddenly.", "そのウサギは突然姿を消した。"],
  "continent": ["Asia is the largest continent.", "アジアは最大の大陸だ。"],
  "geography": ["We studied world geography.", "私たちは世界地理を学んだ。"],
  "ecology": ["Ecology is important today.", "生態系の理解は今日重要だ。"],
  "inhabitant": ["Every inhabitant knew the story.", "住民はみなその話を知っていた。"],
  "suburb": ["They moved to a quiet suburb.", "彼らは静かな郊外へ引っ越した。"],
  "furniture": ["We bought new furniture.", "私たちは新しい家具を買った。"],
  "refrigerator": ["Put the milk in the refrigerator.", "牛乳を冷蔵庫に入れてください。"],
  "garbage": ["Please take out the garbage.", "ごみを出してください。"],
  "trash": ["He threw the cup in the trash.", "彼はそのコップをごみ箱に捨てた。"],
  "litter": ["Don’t drop litter here.", "ここにごみを捨ててはいけない。"],
  "trace": ["There was no trace of him.", "彼の痕跡はまったくなかった。"],
  "row": ["We sat in the front row.", "私たちは前列に座った。"],
  "core": ["Trust is the core of friendship.", "信頼は友情の核心だ。"],
  "orbit": ["The moon moves in orbit.", "月は軌道に沿って動く。"],
  "galaxy": ["Our galaxy contains billions of stars.", "私たちの銀河には何十億もの星がある。"],
  "myth": ["It is just a myth.", "それはただの神話だ。"],
  "faith": ["I have faith in you.", "私はあなたを信じている。"],
  "wisdom": ["Age often brings wisdom.", "年を重ねるとしばしば知恵が身につく。"],
  "obligation": ["I have no obligation to go.", "私には行く義務がない。"],
  "privilege": ["It was a privilege to meet her.", "彼女に会えたのは光栄だった。"],
  "discrimination": ["The law bans discrimination.", "その法律は差別を禁じている。"],
  "ambition": ["Her ambition is to become a doctor.", "彼女の願望は医者になることだ。"],
  "illusion": ["It was only an illusion.", "それはただの錯覚だった。"],
  "instinct": ["Birds fly by instinct.", "鳥は本能で飛ぶ。"],
  "shame": ["It’s a shame you missed it.", "あなたがそれを逃したのは残念だ。"],
  "humor": ["He has a good sense of humor.", "彼にはユーモアのセンスがある。"],
  "courage": ["It took courage to speak out.", "声を上げるには勇気が必要だった。"],
  "sympathy": ["I felt sympathy for him.", "私は彼に同情した。"],
  "tragedy": ["The accident was a tragedy.", "その事故は悲劇だった。"],
  "fate": ["They could not escape fate.", "彼らは運命から逃れられなかった。"],
  "destiny": ["She believed in destiny.", "彼女は運命を信じていた。"],
  "abuse": ["Some athletes abuse drugs.", "一部の選手は薬物を乱用する。"],
  "wound": ["The doctor cleaned the wound.", "医者は傷を消毒した。"],
  "fever": ["He has a high fever.", "彼は高熱がある。"],
  "infection": ["The cut caused an infection.", "その切り傷が感染を引き起こした。"],
  "brave": ["The firefighter was brave.", "その消防士は勇敢だった。"],
  "brilliant": ["That was a brilliant idea.", "それはすばらしい考えだった。"],
  "gentle": ["She has a gentle voice.", "彼女はやさしい声をしている。"],
  "noble": ["He fought for a noble cause.", "彼は高潔な大義のために戦った。"],
  "royal": ["They visited the royal palace.", "彼らは王宮を訪れた。"],
  "sacred": ["This is a sacred place.", "ここは神聖な場所だ。"],
  "holy": ["They walked on holy ground.", "彼らは聖なる地を歩いた。"],
  "decent": ["He earns a decent salary.", "彼はきちんとした給料を得ている。"],
  "grateful": ["I’m grateful for your help.", "あなたの助けに感謝しています。"],
  "fond": ["She is fond of cats.", "彼女は猫が好きだ。"],
  "selfish": ["Don’t be selfish.", "自分勝手になってはいけない。"],
  "awkward": ["It was an awkward silence.", "気まずい沈黙だった。"],
  "awful": ["We had awful weather.", "ひどい天気だった。"],
  "ultimate": ["That is our ultimate goal.", "それが私たちの最終目標だ。"],
  "dynamic": ["She is a dynamic leader.", "彼女は活動的なリーダーだ。"],
  "tremendous": ["They made tremendous progress.", "彼らは大きな進歩を遂げた。"],
  "abundant": ["The region has abundant water.", "その地域には豊富な水がある。"],
  "dull": ["The lecture was dull.", "その講義は退屈だった。"],
  "urgent": ["This is an urgent matter.", "これは緊急の問題だ。"],
  "spare": ["Do you have a spare key?", "予備の鍵を持っていますか。"],
  "tight": ["These shoes feel tight.", "この靴はきつく感じる。"],
  "shallow": ["The water looks shallow.", "その水は浅そうに見える。"],
  "superficial": ["His knowledge was superficial.", "彼の知識は表面的だった。"]
});
Object.assign(window.EXAMPLE_BANK, {
  "greet": ["She greeted me with a smile.", "彼女は笑顔で私にあいさつした。"],
  "chat": ["We chatted after class.", "私たちは授業のあとおしゃべりした。"],
  "remark": ["He remarked on the weather.", "彼は天気について述べた。"],
  "command": ["The officer commanded them to stop.", "その士官は彼らに止まるよう命じた。"],
  "utter": ["She uttered no word.", "彼女はひと言も発しなかった。"],
  "declare": ["They declared the result official.", "彼らはその結果を公式なものと宣言した。"],
  "pronounce": ["Can you pronounce this word?", "この単語を発音できますか。"],
  "correspond": ["The two numbers correspond exactly.", "その2つの数字はぴったり一致する。"],
  "imitate": ["Children often imitate adults.", "子どもはよく大人のまねをする。"],
  "resemble": ["You resemble your mother.", "あなたはお母さんに似ている。"],
  "exhibit": ["The museum exhibits local art.", "その博物館は地元の美術作品を展示している。"],
  "distribute": ["They distributed food to families.", "彼らは家庭に食料を配った。"],
  "attribute": ["Many people attribute success to luck.", "多くの人は成功を運のおかげだと考える。"],
  "evaluate": ["Teachers evaluate students fairly.", "教師は生徒を公平に評価する。"],
  "assess": ["Doctors assessed his condition.", "医師たちは彼の状態を評価した。"],
  "deserve": ["She deserves praise.", "彼女は賞賛に値する。"],
  "weigh": ["The baby weighs three kilos.", "その赤ちゃんの体重は3キロある。"],
  "strengthen": ["Exercise strengthens your muscles.", "運動は筋肉を強くする。"],
  "weaken": ["Illness weakened his body.", "病気で彼の体は弱った。"],
  "approve": ["I approve of your plan.", "私はあなたの計画に賛成だ。"],
  "assign": ["The teacher assigned homework.", "先生は宿題を課した。"],
  "sustain": ["Plants need water to sustain growth.", "植物は成長を維持するのに水が必要だ。"],
  "accomplish": ["She accomplished her goal.", "彼女は目標を成し遂げた。"],
  "relieve": ["This medicine relieved my pain.", "この薬は私の痛みを和らげた。"],
  "frustrate": ["Delays frustrate passengers.", "遅れは乗客をいらだたせる。"],
  "scare": ["Loud noises scare babies.", "大きな音は赤ちゃんを怖がらせる。"],
  "resist": ["He resisted the temptation.", "彼は誘惑に負けなかった。"],
  "protest": ["Students protested against the rule.", "生徒たちはその規則に抗議した。"],
  "shut": ["Please shut the door.", "ドアを閉めてください。"],
  "defeat": ["Our team defeated the champions.", "私たちのチームは優勝チームを破った。"],
  "neglect": ["Don’t neglect your health.", "健康をおろそかにしてはいけない。"],
  "retire": ["My father retired last year.", "私の父は昨年引退した。"],
  "reform": ["The city reformed its school system.", "その市は学校制度を改革した。"],
  "collapse": ["The old bridge collapsed.", "古い橋が崩れた。"],
  "ruin": ["Rain ruined our picnic.", "雨で私たちのピクニックは台無しになった。"],
  "sink": ["The boat sank quickly.", "その船はすぐに沈んだ。"],
  "pile": ["She piled books on the desk.", "彼女は机の上に本を積み重ねた。"],
  "derive": ["Many words derive from Latin.", "多くの語はラテン語に由来する。"],
  "yield": ["This farm yields good rice.", "この農場はよい米を産出する。"],
  "occupy": ["The sofa occupies too much space.", "そのソファは場所を取りすぎる。"],
  "wrap": ["She wrapped the gift carefully.", "彼女はその贈り物をていねいに包んだ。"],
  "embrace": ["She embraced her daughter warmly.", "彼女は娘をあたたかく抱きしめた。"],
  "length": ["What is the length of the table?", "そのテーブルの長さはどれくらいですか。"],
  "height": ["The height of the wall surprised me.", "その壁の高さに私は驚いた。"],
  "volume": ["Please lower the volume.", "音量を下げてください。"],
  "sum": ["He paid a large sum.", "彼は大金を支払った。"],
  "frame": ["The photo is in a silver frame.", "その写真は銀色の額縁に入っている。"],
  "boundary": ["The fence marks the boundary.", "そのフェンスが境界を示している。"],
  "district": ["He lives in my school district.", "彼は私の学区に住んでいる。"],
  "territory": ["Wolves protect their territory.", "オオカミは自分たちの縄張りを守る。"],
  "square": ["Draw a square here.", "ここに正方形を描きなさい。"],
  "empire": ["The empire ruled many lands.", "その帝国は多くの土地を支配した。"],
  "heritage": ["The town protects its cultural heritage.", "その町は文化遺産を守っている。"],
  "fee": ["There is no entry fee.", "入場料はかからない。"],
  "discount": ["Students get a discount.", "学生には割引がある。"],
  "charity": ["She gave money to charity.", "彼女は慈善事業にお金を寄付した。"],
  "mission": ["Their mission was clear.", "彼らの使命は明確だった。"],
  "profession": ["Teaching is a rewarding profession.", "教職はやりがいのある職業だ。"],
  "slave": ["The story is about a slave.", "その物語は奴隷についての話だ。"],
  "witness": ["A witness saw the accident.", "目撃者がその事故を見た。"],
  "incident": ["The incident caused concern.", "その出来事は不安を引き起こした。"],
  "insurance": ["I need car insurance.", "私は自動車保険が必要だ。"],
  "welfare": ["The program supports child welfare.", "その制度は児童福祉を支えている。"],
  "treasure": ["The box held hidden treasure.", "その箱には隠された宝が入っていた。"],
  "leisure": ["Reading is my leisure activity.", "読書は私の余暇の過ごし方だ。"],
  "priority": ["Safety is our top priority.", "安全が私たちの最優先事項だ。"],
  "reputation": ["The restaurant has a good reputation.", "そのレストランは評判がよい。"],
  "honor": ["It was an honor to meet her.", "彼女に会えて光栄だった。"],
  "statue": ["A statue stood in the park.", "公園に像が立っていた。"],
  "architecture": ["I love old architecture.", "私は古い建築が好きだ。"],
  "logic": ["Your argument lacks logic.", "あなたの主張には論理が欠けている。"],
  "mechanism": ["Nobody understood the mechanism fully.", "その仕組みを完全に理解した人はいなかった。"],
  "clue": ["Police found an important clue.", "警察は重要な手がかりを見つけた。"],
  "means": ["Money is not the only means.", "お金だけが手段ではない。"],
  "trap": ["The mouse escaped the trap.", "ネズミはわなから逃げた。"],
  "trick": ["He played a clever trick.", "彼はうまい策略を使った。"],
  "guard": ["A guard checked our bags.", "警備員が私たちのかばんを調べた。"],
  "innocent": ["He was found innocent.", "彼は無罪だとされた。"],
  "guilty": ["She felt guilty afterward.", "彼女はそのあと罪悪感を抱いた。"],
  "rude": ["It is rude to interrupt.", "さえぎるのは失礼だ。"],
  "shy": ["He is shy with strangers.", "彼は見知らぬ人の前では内気だ。"],
  "liberal": ["Her parents are quite liberal.", "彼女の親はかなり寛大だ。"],
  "stupid": ["That was a stupid mistake.", "それはばかな間違いだった。"],
  "reluctant": ["She was reluctant to speak.", "彼女は話すのに気が進まなかった。"],
  "generous": ["He is generous with his time.", "彼は自分の時間を惜しみなく使ってくれる。"],
  "modest": ["She gave a modest reply.", "彼女は控えめな返答をした。"],
  "lonely": ["I felt lonely after moving.", "引っ越したあと私は寂しかった。"],
  "pure": ["The water looks pure.", "その水は純粋に見える。"],
  "grand": ["They stayed in a grand hotel.", "彼らは豪華なホテルに泊まった。"],
  "adequate": ["We have adequate supplies.", "私たちには十分な物資がある。"],
  "apparent": ["His fear was apparent.", "彼の恐れは明らかだった。"],
  "classic": ["This is a classic novel.", "これは古典的な小説だ。"],
  "remote": ["They live in a remote village.", "彼らは遠く離れた村に住んでいる。"],
  "solid": ["The table feels solid.", "その机はしっかりしている。"],
  "raw": ["She ate raw fish.", "彼女は生の魚を食べた。"],
  "plain": ["Please use plain language.", "わかりやすい言葉を使ってください。"],
  "primitive": ["They used primitive tools.", "彼らは原始的な道具を使った。"],
  "steady": ["She made steady progress.", "彼女は着実に進歩した。"],
  "slight": ["I felt a slight pain.", "私はわずかな痛みを感じた。"],
  "subtle": ["The difference is subtle.", "その違いは微妙だ。"],

  "delight": ["The gift delighted her.", "その贈り物は彼女を大喜びさせた。"],
  "entertain": ["The clown entertained the children.", "そのピエロは子どもたちを楽しませた。"],
  "fulfill": ["Hard work fulfilled his dream.", "努力によって彼の夢はかなえられた。"],
  "cheer": ["Her words cheered me up.", "彼女の言葉で私は元気づけられた。"],
  "amuse": ["The joke amused everyone.", "その冗談はみんなを笑わせた。"],
  "anticipate": ["We anticipated heavy traffic.", "私たちはひどい渋滞を予期していた。"],
  "confront": ["We must confront the problem.", "私たちはその問題に立ち向かわなければならない。"],
  "undergo": ["He underwent surgery last week.", "彼は先週手術を受けた。"],
  "exceed": ["Costs exceeded our budget.", "費用は私たちの予算を超えた。"],
  "overwhelm": ["The amount of work overwhelmed me.", "その仕事量に私はまいってしまった。"],
  "shoot": ["The hunter shot a deer.", "その猟師は鹿を撃った。"],
  "murder": ["The film showed a murder.", "その映画には殺人の場面があった。"],
  "rob": ["Two men robbed the bank.", "2人の男が銀行を襲った。"],
  "deprive": ["The noise deprived me of sleep.", "その騒音で私は眠れなかった。"],
  "rid": ["This medicine rid me of pain.", "この薬で私は痛みから解放された。"],
  "interrupt": ["Please don’t interrupt me.", "話をさえぎらないでください。"],
  "interfere": ["Don’t interfere with their plans.", "彼らの計画のじゃまをしないで。"],
  "bully": ["Some students bullied him online.", "何人かの生徒がネット上で彼をいじめた。"],
  "defend": ["Soldiers defended the town.", "兵士たちはその町を守った。"],
  "rescue": ["Firefighters rescued the child.", "消防士たちはその子どもを救助した。"],
  "accuse": ["She accused him of lying.", "彼女は彼がうそをついたと非難した。"],
  "sue": ["They sued the company.", "彼らはその会社を訴えた。"],
  "wander": ["We wandered around the city.", "私たちは町をぶらぶら歩き回った。"],
  "chase": ["The dog chased the cat.", "その犬は猫を追いかけた。"],
  "arrest": ["Police arrested the suspect.", "警察は容疑者を逮捕した。"],
  "submit": ["Please submit your report today.", "今日中にレポートを提出してください。"],
  "punish": ["Teachers should not punish unfairly.", "教師は不公平に罰してはならない。"],
  "resolve": ["We resolved the conflict peacefully.", "私たちはその対立を平和的に解決した。"],
  "justify": ["Nothing can justify violence.", "何ものも暴力を正当化できない。"],
  "restore": ["They restored the old temple.", "彼らは古い寺を修復した。"],
  "modify": ["We modified the plan slightly.", "私たちはその計画を少し修正した。"],
  "impose": ["The school imposed strict rules.", "その学校は厳しい規則を課した。"],
  "compose": ["Ten players compose the team.", "10人の選手がそのチームを構成している。"],
  "classify": ["We classified the books by topic.", "私たちは本を話題ごとに分類した。"],
  "substitute": ["You can substitute honey for sugar.", "砂糖の代わりにハチミツを使えます。"],
  "shrink": ["My sweater shrank in the wash.", "私のセーターは洗って縮んだ。"],
  "lean": ["He leaned against the wall.", "彼は壁にもたれかかった。"],
  "fold": ["Please fold the paper in half.", "その紙を半分に折ってください。"],
  "load": ["They loaded the truck quickly.", "彼らはすばやくトラックに積み込んだ。"],
  "pour": ["She poured tea into the cup.", "彼女はカップにお茶を注いだ。"],
  "float": ["The boat floated on the lake.", "そのボートは湖に浮かんでいた。"],
  "shine": ["Stars shone brightly.", "星が明るく輝いていた。"],
  "editor": ["The editor checked my article.", "編集者が私の記事を確認した。"],
  "poetry": ["She enjoys reading poetry.", "彼女は詩を読むのを楽しんでいる。"],
  "usage": ["Check the word’s usage here.", "ここでその語の使い方を確認しなさい。"],
  "sector": ["Tourism is a growing sector.", "観光業は成長している分野だ。"],
  "span": ["The bridge has a long span.", "その橋は長い支間を持っている。"],
  "literacy": ["The program improved literacy rates.", "その計画で読み書き能力の割合が向上した。"],
  "symptom": ["Fever is a common symptom.", "熱はよくある症状だ。"],
  "phase": ["We entered a new phase.", "私たちは新しい段階に入った。"],
  "surgery": ["She had heart surgery.", "彼女は心臓の手術を受けた。"],
  "virus": ["The virus spread rapidly.", "そのウイルスは急速に広がった。"],
  "poison": ["The bottle contained poison.", "そのびんには毒が入っていた。"],
  "protein": ["Eggs are rich in protein.", "卵はたんぱく質が豊富だ。"],
  "liquid": ["Water is a clear liquid.", "水は透明な液体だ。"],
  "oxygen": ["Plants produce oxygen.", "植物は酸素を生み出す。"],
  "globe": ["News spread across the globe.", "そのニュースは世界中に広まった。"],
  "pole": ["The North Pole is icy.", "北極は氷に覆われている。"],
  "valley": ["A river runs through the valley.", "谷を川が流れている。"],
  "conservation": ["The group supports forest conservation.", "その団体は森林保護を支援している。"],
  "channel": ["We changed the TV channel.", "私たちはテレビのチャンネルを変えた。"],
  "glacier": ["The glacier is melting fast.", "その氷河は急速に溶けている。"],
  "pioneer": ["She was a pioneer in science.", "彼女は科学分野の先駆者だった。"],
  "prospect": ["Job prospects look good.", "仕事の見込みはよさそうだ。"],
  "enthusiasm": ["The students showed real enthusiasm.", "生徒たちは本当の熱意を見せた。"],
  "passion": ["She has a passion for music.", "彼女は音楽に情熱を持っている。"],
  "fortune": ["He made a fortune in business.", "彼は商売で財産を築いた。"],
  "obstacle": ["Lack of time was an obstacle.", "時間不足が障害だった。"],
  "prejudice": ["We must fight prejudice.", "私たちは偏見と戦わなければならない。"],
  "justice": ["They demanded justice.", "彼らは正義を求めた。"],
  "opponent": ["He respected his opponent.", "彼は対戦相手を尊重した。"],
  "sacrifice": ["Success often requires sacrifice.", "成功にはしばしば犠牲が必要だ。"],
  "fault": ["The accident was my fault.", "その事故は私の責任だった。"],
  "prison": ["The criminal was sent to prison.", "その犯罪者は刑務所へ送られた。"],
  "shelter": ["We took shelter from the rain.", "私たちは雨宿りした。"],
  "committee": ["The committee met today.", "委員会は今日開かれた。"],
  "ritual": ["Morning tea is his ritual.", "朝のお茶は彼の日課のような儀式だ。"],
  "mature": ["She is mature for her age.", "彼女は年齢のわりに大人びている。"],
  "moderate": ["Exercise at a moderate pace.", "適度なペースで運動しなさい。"],
  "neutral": ["Try to stay neutral.", "中立を保つようにしなさい。"],
  "optimistic": ["She feels optimistic about the future.", "彼女は将来について楽観的だ。"],
  "pessimistic": ["He is pessimistic about the result.", "彼は結果について悲観的だ。"],
  "radical": ["They proposed radical changes.", "彼らは根本的な変化を提案した。"],
  "rough": ["The road is rough here.", "ここの道はでこぼこしている。"],
  "smooth": ["Her skin feels smooth.", "彼女の肌はなめらかだ。"],
  "fluent": ["She speaks fluent English.", "彼女は流ちょうな英語を話す。"],
  "casual": ["He wore casual clothes.", "彼は普段着を着ていた。"],
  "instant": ["We got an instant reply.", "私たちはすぐに返事をもらった。"],
  "incredible": ["That was an incredible performance.", "それは信じられないほどすばらしい演技だった。"],
  "genuine": ["Her smile was genuine.", "彼女の笑顔は本物だった。"],
  "precious": ["Time is precious.", "時間は貴重だ。"],
  "prominent": ["She is a prominent scientist.", "彼女は著名な科学者だ。"],
  "blind": ["The blind man crossed carefully.", "その目の不自由な男性は注意深く渡った。"],
  "deaf": ["The boy was born deaf.", "その少年は耳が聞こえない状態で生まれた。"],
  "harsh": ["Winter is harsh there.", "そこでは冬が厳しい。"],
  "prompt": ["Thank you for your prompt reply.", "早いご返事をありがとうございます。"],
  "inevitable": ["Change is inevitable.", "変化は避けられない。"],
  "marine": ["We studied marine animals.", "私たちは海の動物について学んだ。"],
  "tropical": ["They visited a tropical island.", "彼らは熱帯の島を訪れた。"],
  "Arctic": ["Polar bears live in the Arctic.", "ホッキョクグマは北極に住んでいる。"],

  "forecast": ["The forecast says rain tomorrow.", "天気予報では明日は雨だ。"],
  "speculate": ["Experts speculated about the cause.", "専門家たちはその原因について推測した。"],
  "bet": ["I bet he forgot.", "彼は忘れたに違いないと思う。"],
  "quote": ["She quoted her teacher.", "彼女は先生の言葉を引用した。"],
  "consult": ["You should consult a doctor.", "医者に相談すべきだ。"],
  "dispute": ["They disputed the decision.", "彼らはその決定に異議を唱えた。"],
  "accumulate": ["Dust accumulated on the shelf.", "ほこりが棚に積もった。"],
  "grasp": ["He finally grasped the idea.", "彼はついにその考えを理解した。"],
  "grip": ["She gripped my hand tightly.", "彼女は私の手をしっかり握った。"],
  "seize": ["Police seized the drugs.", "警察はその薬物を押収した。"],
  "comprehend": ["I couldn’t comprehend his answer.", "私は彼の答えを理解できなかった。"],
  "constitute": ["Women constitute half the class.", "女性がクラスの半分を占めている。"],
  "reinforce": ["Praise reinforces good habits.", "ほめることはよい習慣を強化する。"],
  "resort": ["They resorted to violence.", "彼らは暴力に訴えた。"],
  "donate": ["We donated old clothes.", "私たちは古着を寄付した。"],
  "obey": ["Children should obey traffic rules.", "子どもは交通ルールに従うべきだ。"],
  "dedicate": ["She dedicated her life to teaching.", "彼女は一生を教育にささげた。"],
  "transmit": ["Radios transmit signals.", "ラジオは信号を送る。"],
  "equip": ["The school equipped each room with computers.", "その学校は各教室にコンピューターを備えつけた。"],
  "bind": ["The rope bound his hands.", "ロープが彼の手をしばっていた。"],
  "pose": ["The change poses a risk.", "その変化は危険をもたらす。"],
  "pause": ["He paused for a moment.", "彼は少しの間立ち止まった。"],
  "hesitate": ["Don’t hesitate to ask questions.", "遠慮せず質問してください。"],
  "split": ["We split the bill.", "私たちは勘定を割り勘にした。"],
  "bend": ["Bend your knees slightly.", "ひざを少し曲げてください。"],
  "tap": ["He tapped me on the shoulder.", "彼は私の肩を軽くたたいた。"],
  "boil": ["Boil the water first.", "まず水を沸かしてください。"],
  "bow": ["The actors bowed to the audience.", "俳優たちは観客におじぎをした。"],
  "conceal": ["He concealed his feelings.", "彼は気持ちを隠した。"],
  "dispose": ["Please dispose of the trash properly.", "ごみは適切に処分してください。"],
  "cheat": ["He cheated on the test.", "彼はテストでカンニングした。"],
  "distract": ["Noise distracts me easily.", "騒音があると私はすぐ気が散る。"],
  "exclude": ["The price excludes tax.", "その価格には税が含まれていない。"],
  "astonish": ["Her courage astonished us.", "彼女の勇気に私たちは驚いた。"],
  "thrill": ["The game thrilled the crowd.", "その試合は観衆をわくわくさせた。"],
  "leap": ["The cat leaped onto the table.", "その猫はテーブルの上に飛び乗った。"],
  "postpone": ["They postponed the meeting.", "彼らは会議を延期した。"],
  "dismiss": ["The company dismissed two workers.", "その会社は2人の労働者を解雇した。"],
  "resign": ["He resigned from his job.", "彼は仕事を辞めた。"],
  "withdraw": ["She withdrew some cash.", "彼女は現金を少し引き出した。"],
  "fade": ["The colors faded in the sun.", "その色は日に当たってあせた。"],
  "vanish": ["The rabbit vanished suddenly.", "そのウサギは突然姿を消した。"],
  "continent": ["Asia is the largest continent.", "アジアは最大の大陸だ。"],
  "geography": ["We studied world geography.", "私たちは世界地理を学んだ。"],
  "ecology": ["Ecology is important today.", "生態系の理解は今日重要だ。"],
  "inhabitant": ["Every inhabitant knew the story.", "住民はみなその話を知っていた。"],
  "suburb": ["They moved to a quiet suburb.", "彼らは静かな郊外へ引っ越した。"],
  "furniture": ["We bought new furniture.", "私たちは新しい家具を買った。"],
  "refrigerator": ["Put the milk in the refrigerator.", "牛乳を冷蔵庫に入れてください。"],
  "garbage": ["Please take out the garbage.", "ごみを出してください。"],
  "trash": ["He threw the cup in the trash.", "彼はそのコップをごみ箱に捨てた。"],
  "litter": ["Don’t drop litter here.", "ここにごみを捨ててはいけない。"],
  "trace": ["There was no trace of him.", "彼の痕跡はまったくなかった。"],
  "row": ["We sat in the front row.", "私たちは前列に座った。"],
  "core": ["Trust is the core of friendship.", "信頼は友情の核心だ。"],
  "orbit": ["The moon moves in orbit.", "月は軌道に沿って動く。"],
  "galaxy": ["Our galaxy contains billions of stars.", "私たちの銀河には何十億もの星がある。"],
  "myth": ["It is just a myth.", "それはただの神話だ。"],
  "faith": ["I have faith in you.", "私はあなたを信じている。"],
  "wisdom": ["Age often brings wisdom.", "年を重ねるとしばしば知恵が身につく。"],
  "obligation": ["I have no obligation to go.", "私には行く義務がない。"],
  "privilege": ["It was a privilege to meet her.", "彼女に会えたのは光栄だった。"],
  "discrimination": ["The law bans discrimination.", "その法律は差別を禁じている。"],
  "ambition": ["Her ambition is to become a doctor.", "彼女の願望は医者になることだ。"],
  "illusion": ["It was only an illusion.", "それはただの錯覚だった。"],
  "instinct": ["Birds fly by instinct.", "鳥は本能で飛ぶ。"],
  "shame": ["It’s a shame you missed it.", "あなたがそれを逃したのは残念だ。"],
  "humor": ["He has a good sense of humor.", "彼にはユーモアのセンスがある。"],
  "courage": ["It took courage to speak out.", "声を上げるには勇気が必要だった。"],
  "sympathy": ["I felt sympathy for him.", "私は彼に同情した。"],
  "tragedy": ["The accident was a tragedy.", "その事故は悲劇だった。"],
  "fate": ["They could not escape fate.", "彼らは運命から逃れられなかった。"],
  "destiny": ["She believed in destiny.", "彼女は運命を信じていた。"],
  "abuse": ["Some athletes abuse drugs.", "一部の選手は薬物を乱用する。"],
  "wound": ["The doctor cleaned the wound.", "医者は傷を消毒した。"],
  "fever": ["He has a high fever.", "彼は高熱がある。"],
  "infection": ["The cut caused an infection.", "その切り傷が感染を引き起こした。"],
  "brave": ["The firefighter was brave.", "その消防士は勇敢だった。"],
  "brilliant": ["That was a brilliant idea.", "それはすばらしい考えだった。"],
  "gentle": ["She has a gentle voice.", "彼女はやさしい声をしている。"],
  "noble": ["He fought for a noble cause.", "彼は高潔な大義のために戦った。"],
  "royal": ["They visited the royal palace.", "彼らは王宮を訪れた。"],
  "sacred": ["This is a sacred place.", "ここは神聖な場所だ。"],
  "holy": ["They walked on holy ground.", "彼らは聖なる地を歩いた。"],
  "decent": ["He earns a decent salary.", "彼はきちんとした給料を得ている。"],
  "grateful": ["I’m grateful for your help.", "あなたの助けに感謝しています。"],
  "fond": ["She is fond of cats.", "彼女は猫が好きだ。"],
  "selfish": ["Don’t be selfish.", "自分勝手になってはいけない。"],
  "awkward": ["It was an awkward silence.", "気まずい沈黙だった。"],
  "awful": ["We had awful weather.", "ひどい天気だった。"],
  "ultimate": ["That is our ultimate goal.", "それが私たちの最終目標だ。"],
  "dynamic": ["She is a dynamic leader.", "彼女は活動的なリーダーだ。"],
  "tremendous": ["They made tremendous progress.", "彼らは大きな進歩を遂げた。"],
  "abundant": ["The region has abundant water.", "その地域には豊富な水がある。"],
  "dull": ["The lecture was dull.", "その講義は退屈だった。"],
  "urgent": ["This is an urgent matter.", "これは緊急の問題だ。"],
  "spare": ["Do you have a spare key?", "予備の鍵を持っていますか。"],
  "tight": ["These shoes feel tight.", "この靴はきつく感じる。"],
  "shallow": ["The water looks shallow.", "その水は浅そうに見える。"],
  "superficial": ["His knowledge was superficial.", "彼の知識は表面的だった。"]
});
